### ISSUE TITLE
Why did adding Bishops cause this position to be incorrectly scored

### ISSUE THREAD

**Issue by AFDudley** [official-stockfish/Stockfish#1033]
https://en.lichess.org/analysis/8/p7/kpP5/qrp1b3/rpP2b2/pP4b1/P3K3/8_w_-_-

Sorry, if this is considered spam. But i'm pretty sure there is some sort of position compression that is missing from stockfish such that adding these bishops is confusing the engine; A bishop on the B8-H2 diagonal should be seen as the only requisite and the other two bishop positions should be seen as irrelevant/compressible. Maybe it's just scoring "two bishops" without considering they are on the same color?

https://en.lichess.org/study/eCEJMbkq Illustrates the point a little more directly.

**Comment by dsjoerg** [comment]
Hi!  As it turns out there is no "position compression" in the way that you are thinking of it in Stockfish.

The core of most chess engines is looking ahead deep into the future, and then at some point doing "static evaluations" of the future positions.  This is a great approach for real/normal chess but fails horribly on some toy/puzzle examples like this one.

As I understand it, it's not a priority for the Stockfish engine to be able to correctly evaluate/solve puzzles like this.  However if one wanted to build an engine that was good at solving chess puzzles, that would certainly be possible (and interesting!)

If you're interested in digging further into these topic I can recommend some reading.

Welcome to the chess-programming party :)

**Comment by ddugovic** [comment]
While there is no "compression", I would expect that with only 1 bishop the hash table hit rate would quickly approach 100%.

**Comment by RSFalcon7** [comment]
@dsjoerg I would like to understand a bit more how stockfish works and how can I contribute.
This puzzle specifically sounds like it should be able to, at least, detect that black can not move anything but the bishops and white can force a draw with the 50th moves rule by only moving the king.

**Comment by dsjoerg** [comment]
@RSFalcon7 here's a good page to start with: http://chess.stackexchange.com/questions/2204/how-do-chess-engines-think

From the 10,000 big-picture view, Stockfish is similar to other chess engines in all respects.  What makes it outstanding among chess engines is its clean code, its active community of contributors, its testing & improvement methodology, and the many clever ideas added by many contributors over the years, to name a few.

But in terms of the question being asked here, what can be said about Stockfish could be said about nearly any other chess engine.  Chess engines do not "think" in terms of the invariant properties of the position in the way that humans do (although one could try to build an engine that thinks in terms of invariants!  would be interesting)

**Comment by dsjoerg** [comment]
Furthermore, @RSFalcon7 I should stress that solving puzzles such as this is not a priority for Stockfish or its contributor community (as far as I can tell) because solving puzzles like this is not related to winning real chess games.

That said, perhaps there are real endgame situations (e.g. positions involving fortresses) which, if engines could do a better job on them, they would also as a consequence do a better job on puzzles like these.

Regarding fortresses, I did a quick search and found this paper by two of my favorite chess-programming authors: https://ailab.si/matej/doc/Detecting_Fortresses_in_Chess.pdf

**Comment by AFDudley** [comment]
I'm pretty busy, but i'm just going to leave this here:
https://github.com/official-stockfish/Stockfish/issues/878

Thanks for the comments and support, it would take me a long time to get up to speed to contribute code to these types of problems, but I have money that I would be willing to contribute.

**Comment by zamar** [comment]
This issue tracker is for bugs

In this case, there is no bug.

**Comment by RSFalcon7** [comment]
Do you have a forum or anything where the developers get organized with next tasks?

**Comment by stockfishdeveloper** [comment]
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking
