### ISSUE TITLE
wrong bench for stated for VoyagerOne's patch

### ISSUE THREAD

**Issue by tthsqe12** [official-stockfish/Stockfish#1058]
Author: VoyagerOne
Date: Fri Apr 7 17:02:31 2017 -0700
Timestamp: 1491609751

stated bench: 6340591
correct bench: 6207458

**Comment by tthsqe12** [comment]
however, this line in stockfish code is non-deterministic
https://github.com/official-stockfish/Stockfish/blob/master/src/movepick.cpp#L243
so it might not be completely VO's fault.

**Comment by vondele** [comment]
@tthsqe12 why would this be non-deterministic ? It is not stable, but it is deterministic.

I think the issue can be closed.

**Comment by tthsqe12** [comment]
I mean that that line can be implement by the compiler however it wants.
If different compilers do it differently, then you will almost surely get different benches.
At some point between SF5 and SF7 the implementation of that line by gcc changed.
I do not like 'well everyone has been getting the same results' so lets not care about it.
If a stable sort is desired, then it should be specified. Otherwise, the specific implementation needs to be specified.
That line of code is a thorn in the side of an otherwise didactic and pedantically compliant code base.

**Comment by vondele** [comment]
ah, I see. I agree, the result is (libstdc++) implementation defined, which is not desirable.

**Comment by vondele** [comment]
I tested using stable_partition in the past, but the result wouldn't even pass a [-3,1]:
http://tests.stockfishchess.org/tests/view/585cdfd00ebc5903140c6082
So, either one provides an implementation of partition with SF, or one accepts this behavior.

**Comment by mstembera** [comment]
If this ever becomes actionable here is one possible solution.
http://tests.stockfishchess.org/tests/view/58d4d3460ebc59035df3315c

**Comment by VoyagerOne** [comment]
@tthsqe12 
The bench changed because while waiting for my patch to be merged.... another functional patch was merged to master... so the bench changed when merging with the master with the new functional patch.

Non-stable partition will always be deterministic among different compilers.

Compilers provide optimizations...not functional changes to code.

**Comment by mstembera** [comment]
@VoyagerOne 
It's no a matter of compiler optimizations.  Whoever implements std::partition is free to do it in any way they like.  Therefore it's possible that results on different platforms will differ.  So far we haven't seen that though.

**Comment by vondele** [comment]
@mstembera I have started a test based on your implementation to fix this issue
http://tests.stockfishchess.org/tests/view/58ef09ba0ebc59035df3399b

**Comment by mstembera** [comment]
@vondele    Glad it was useful.  If I can clean up my code a bit I'd prefer 
```C++
for (ExtMove *sortedEnd = begin+1, *p = begin+1; p < end; ++p)
```
because there is no reason to declare sortedEnd outside the for loop.
Also regarding the comment..  The partial insertion is not stable but it is deterministic so it does solve our problem since the implementation will be the same everywhere.

**Comment by vondele** [comment]
@mstembera thanks for the code and comment, I'll include it in the PR.
