### ISSUE TITLE
Define Stockfish interface

### ISSUE THREAD

**Issue by beyondCritics** [official-stockfish/Stockfish#1228]
A documentation of Stockfish's interpretation of the UCI option language is missing.
There is an attempt to to mitigate this here (http://support.stockfishchess.org/kb/advanced-topics/engine-parameters), but it is outdated and incomplete.

IMHO it is very important to unambigously define the intended meaning of all official options in a document that is maintained together with the source code:

- Allows to validate implementation against the specification
- Allows developers to script stockfish 
- Explain known quirks and pitfalls
- Define applicability  of options and their domain
- ...

**Comment by syzygy1** [comment]
Somewhat more ambitious: come up with a new chess engine interface protocol that standardises (to some extent) the more common options, gets rid of the overhead of the UCI protocol while remaining simple to implement (but no need to pretend statelessness: game play should be controlled by the GUI, but the board state may be maintained by the engine), and finally fixes some of the real shortcomings like the impossibility to communicate engine and opponent ratings.

**Comment by mcostalba** [comment]
Somewhat even more ambitious: to find someone to do the job:

This issue will remain open only for a time, after that I will close it (including the mine on exceptions). As other open source project this is driven by people writing code, not people asking features and should remain like this....anyhow there is always talkchess forum for the wish lists :-)

P.S: statelessness is the best feature of UCI. UCI overhead is only an illusion in the mind of people quantitative-tests challenged.

**Comment by beyondCritics** [comment]
I understand, that statelessness is some sort of self healing feature, designed to wash out bugs of unripe interface implementations. In my experience, if someone introduces an interface bug into stockfish, he will receive a storm of bug reports at the very next day ([as it should be](https://en.wikipedia.org/wiki/Release_early,_release_often)), so stockfish does not need that, except for going silently over bugs of others.

I think that UCI is a dead protocol since 20 years. Nowadays stockfish rules, not them. And the stockfish team has all the right in the world to define and control its own interface. No company in the world would allow others to control its own interface. Other parties, as intelligent and deserving they may be, simply do not have the power, to touch the UCI protocol in any way.

Back in the days, when open source tools were scarce and everyone was on his own little island, it made sense to develop something self contained, i.e. a text based protocol. But nowadays, fluency and connectivity has gotten much more important. For example, compare the interface of [MongoDB](https://docs.mongodb.com/ecosystem/drivers/) with SQL: There is no text interface, but instead an array of drivers. Thus it is extremly easy, to access MongoDB from any modern language. 

My suggestion would be a binary interface to stockfish, 100% backward compatible, with a working upgrade plan and being relative friendly and cooperative to vendors of commercial and open source third party tools.

For example, i could produce a fork doing the following (first draft, alpha):
Stockfish source would be split into three parts:

1. A library with a documented binary interface, defining the documented stockfish interface.
2. A library on top of that, moving on its own pace, defining a documented binary uci interface.
3. An executable, linking against the binary uci interface, providing UCI as it is today.

Such a move would be surely perceived as a threat towards tons of existing software. Furthermore, commercial vendors would face licensing problems. So my first question, without any commitment to detail, what do the copyright holders think about that?

**Comment by mcostalba** [comment]
@beyondCritics I miss who is supposed to be the target user of your effort. GUI developers? Other engines?

If it is the GUI, then I'd strongly suggest to share your ideas with them, perhaps on takchess forum, before to start writing code...

**Comment by syzygy1** [comment]
I agree with Marco that this is not the proper place to discuss a UCI replacement, even though I brought up the point (because it would be good if there were a standard way of setting contempt for a particular side).

But if UCI is to be replaced or updated, I really see no reason for a binary interface. What annoys me most about UCI is that a UCI engine cannot be properly debugged from the command line (this could be remedied by extending the text interface, but still).

**Comment by mcostalba** [comment]
@syzygy1 UCI is a good protocol but can be surely improved, for instance there is no way to signal an error condition back to the GUI, another thing I'd change is a way to read current value of an option (with UCI the GUI can read just default value (I never understood this design choice). But, again, this is not the write place to start this discussion.

**Comment by beyondCritics** [comment]
Just a few points:
A binary interface is the most simple interface to use for others. Instead of implementing the uci protocol within any script languages again and again, this could be solved once and for all. UCI (and stockfish) is insecure, this could be solved too. Other chess programmers could code against a library, saving them work. 
@syzygy1 For some known applications, the UCI interface is just too slow, e.g. [FinalGen](http://chessprogramming.wikispaces.com/FinalGen) could need a binary interface to solve certain leaf positions.
@mcostalba Mentioning the word "UCI" at talkchess is a good method to produce a flame war. To survive, i think i will first present some sort of prototype.

**Comment by lucasart** [comment]
UCI is fine, and you are really misguided if you think that a binary protocol will be faster. The time sent parsing UCI commands is totally negligible (including position moves parsing). This effort is guaranteed to be a waste of time. There's no way you'll get a critical mass of engines and GUI to implement your protocol, especially if it brings no axded value.

As for the UCI protocol flaws, the main one that Marco mentioned (error reporting) is a feature. Input is assumed to be correct (because it comes from another program not a monkey typing random stuff on a keyboard). It saves engine programmers from writing tons of input validation code. Of course there are incorrigible trolls out there, who still can't understand it…

**Comment by beyondCritics** [comment]
> UCI is fine, and you are really misguided if you think that a binary protocol will be faster. The time sent parsing UCI commands is totally negligible (including position moves parsing). 

The most expensive part is likely the system call, not the move parsing.
I understand, that UCI works for you, but did you read my postings where i had proposed the new application with FinalGen as an example? How do you do that with UCI?

> As for the UCI protocol flaws, the main one that Marco mentioned (error reporting) is a feature. Input is assumed to be correct (because it comes from another program not a monkey typing random stuff on a keyboard). It saves engine programmers from writing tons of input validation code. Of course there are incorrigible trolls out there, who still can't understand it…

From your posting it is obvious (again), that you cannot properly distinguish between a alleged bug and a vulnerability and unfortunately you are not the only amateur failing in that regard.
And no, it is not about trolling you. It is because i feel that the public expects that security concerns are taking seriously, i think they can demand that.

**Comment by syzygy1** [comment]
FinalGen invokes Stockfish for millions of leaf node searches?
The slow part will be the searches (milliseconds if not seconds?), not the invocations. The nuisance of having to send the whole move list should not apply, since FinalGen can send the fen directly. 

There may be applications that need very tight integration with SF, but those that need that can make use of the open-source nature of SF. Turning SF into a library is not the focus of SF development.

SF vulnerabilities are not an issue. SF is supposed to be invoked by a trusted program that sends valid input. There is simply no security issue here. Users are not supposed to run SF themselves on unvalidated input. If they still do so, that is at their risk. (Like it is at a user's risk to meddle with C programming and gcc.)

Btw, I suspect Marco was thinking of reporting errors like "failed to allocate 16 GB of hash" rather than "invalid fen".
