### ISSUE TITLE
crash when evaluating valid FEN?

### ISSUE THREAD

**Issue by mmcnl** [official-stockfish/Stockfish#1359]
With the current development build on OSX (and with version 8 on Linux), the following position FEN `2b1kbnQ/rpq1pp1p/2n3p1/8/8/2P5/PP3PPP/RN2KBNR b KQk - 0 9` results in a segmentation fault when asked to go beyond a certain depth (it varies a bit but is usually around 4-6):
```
❯ ./stockfish
Stockfish 090118 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
position fen 2b1kbnQ/rpq1pp1p/2n3p1/8/8/2P5/PP3PPP/RN2KBNR b KQk - 0 9
go depth 3
info depth 1 seldepth 1 multipv 1 score cp -112 nodes 65 nps 32500 tbhits 0 time 2 pv g8f6
info depth 2 seldepth 2 multipv 1 score cp -92 nodes 155 nps 77500 tbhits 0 time 2 pv g8f6 g2g3 c7e5 g1e2
info depth 3 seldepth 4 multipv 1 score cp -92 nodes 240 nps 120000 tbhits 0 time 2 pv g8f6 g2g3 c7e5 g1e2
bestmove g8f6 ponder g2g3
go depth 4
info depth 1 seldepth 1 multipv 1 score cp -92 nodes 45 nps 45000 tbhits 0 time 1 pv g8f6
info depth 2 seldepth 2 multipv 1 score cp -125 nodes 132 nps 66000 tbhits 0 time 2 pv g8f6 b1d2 c7e5 g1e2
info depth 3 seldepth 4 multipv 1 score cp -75 nodes 230 nps 115000 tbhits 0 time 2 pv g8f6 g1f3 e8c8
info depth 4 seldepth 4 multipv 1 score cp -140 nodes 382 nps 191000 tbhits 0 time 2 pv g8f6 g1f3 e8c8 b1d2
bestmove g8f6 ponder g1f3
go depth 5
info depth 1 seldepth 1 multipv 1 score cp -140 nodes 45 nps 45000 tbhits 0 time 1 pv g8f6
info depth 2 seldepth 2 multipv 1 score cp -88 nodes 87 nps 43500 tbhits 0 time 2 pv g8f6 g1f3 e8c8
info depth 3 seldepth 3 multipv 1 score cp -140 nodes 144 nps 72000 tbhits 0 time 2 pv g8f6 g1f3 e8c8
info depth 4 seldepth 4 multipv 1 score cp -140 nodes 189 nps 94500 tbhits 0 time 2 pv g8f6 g1f3 e8c8 b1d2
info depth 5 seldepth 6 multipv 1 score cp -70 nodes 536 nps 178666 tbhits 0 time 3 pv g8f6 g1f3 b7b6 b2b3 e8c8
bestmove g8f6 ponder g1f3
go depth 6
info depth 1 seldepth 1 multipv 1 score cp -70 nodes 45 nps 45000 tbhits 0 time 1 pv g8f6
info depth 2 seldepth 2 multipv 1 score cp -70 nodes 89 nps 89000 tbhits 0 time 1 pv g8f6 g1f3
info depth 3 seldepth 3 multipv 1 score cp -70 nodes 129 nps 129000 tbhits 0 time 1 pv g8f6 g1f3 b7b6
info depth 4 seldepth 4 multipv 1 score cp -70 nodes 178 nps 89000 tbhits 0 time 2 pv g8f6 g1f3 b7b6 b2b3
[1]    46863 segmentation fault  ./stockfish
```
I'm aware of a similar issue when stockfish is given invalid FENs (https://github.com/official-stockfish/Stockfish/issues/1253) but as far as I can tell, this FEN is valid.
Any insights?
Thanks much!

**Comment by MichaelB7** [comment]
The fen is invalid. Black cannot castle kingside  as the fen indicates since the white queen is in the rook position.  Some GUIs, like xBoard, will automatically correct and drop the extraneous "k" from the fen if copy it back out.
<< Confirmation: Debug set to log.txt
>> p f 2b1kbnQ/rpq1pp1p/2n3p1/8/8/2P5/PP3PPP/RN2KBNR b KQk - 0 9 {"p f" is a keyboard shortcut for "position fen"}
>> d
<< 
<<  +---+---+---+---+---+---+---+---+
<<  |   |   | b |   | k | b | n | Q |
<<  +---+---+---+---+---+---+---+---+
<<  | r | p | q |   | p | p |   | p |
<<  +---+---+---+---+---+---+---+---+
<<  |   |   | n |   |   |   | p |   |
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |
<<  +---+---+---+---+---+---+---+---+
<<  |   |   | P |   |   |   |   |   |
<<  +---+---+---+---+---+---+---+---+
<<  | P | P |   |   |   | P | P | P |
<<  +---+---+---+---+---+---+---+---+
<<  | R | N |   |   | K | B | N | R |
<<  +---+---+---+---+---+---+---+---+
<< 
<< Fen: 2b1kbnQ/rpq1pp1p/2n3p1/8/8/2P5/PP3PPP/RN2KBNR b KQq - 0 9
<< Key: C39E235F9C454440
<< Checkers: 
>> g i {keyboard shortcut for "go infinite"}
<< info depth 1 seldepth 1 multipv 1 score cp -107 nodes 66 nps 66000 tbhits 0 time 1 pv g8f6
<< info depth 2 seldepth 2 multipv 1 score cp -84 nodes 156 nps 156000 tbhits 0 time 1 pv g8f6 g2g3 c7e5 g1e2
<< info depth 3 seldepth 4 multipv 1 score cp -84 nodes 244 nps 244000 tbhits 0 time 1 pv g8f6 g2g3 c7e5 g1e2
```
Segmentation fault: 11

**Comment by mmcnl** [comment]
ah, thanks for the information, @MichaelB7. Apologies for the spurious issue.
