### ISSUE TITLE
Potential contradiction in passed pawn evaluation 

### ISSUE THREAD

**Issue by singaurav** [official-stockfish/Stockfish#1513]
```
b = pe->passed_pawns(Us);
while (b) {
    Square s = pop_lsb(&b);
    if (   !pos.pawn_passed(Us, s + Up) 
            || (pos.pieces(PAWN) & forward_file_bb(Us, s)))
            bonus = bonus / 2;
}
```
**While** loop is only run for passed pawns.
**If** condition inside the while loop tests if the pawn is 'not passed' when moving up.
How can a pawn be passed on s but not passed on s + Up?

**Comment by Hanamuke** [comment]
At the very least, this condition is functional, removing it changes the bench. It isn't obvious why, the comment suggests that is only a passed candidate. Maybe making the code a bit more self-explanatory would help, but I don't understand it myself.

**Comment by Hanamuke** [comment]
A comment in pawns.cpp state
`// Passed pawns will be properly scored in evaluation because we need
 // full attack info to evaluate them. Include also not passed pawns
// which could become passed after one or two pawn pushes when are
// not attacked more times than defended.`

So that is why, but it is indeed obscure to call passed_pawns a variable that contains not only that. It would be the same problem with "candidate_passers". I suggest you close this issue and post in the issue called RENAIMING THREAD

**Comment by Rocky640** [comment]
pe->passed_pawns(Us); //contains  some true and some candidate pawns 
(see pawns.cpp where we build the passedPawns[Us])

3 examples of candidate pawns and how they will be scored:

white b4 c3 against black a5    whatever black do, (assuming only pawns on the board...)
white will end up with a passed pawn after one push. Full bonus is given.

white a4 b4 c3 against black a5 c6  
b4 is a candidate passed pawn, with enough support to be a true passed pawn, but 2 pushes are necessary to be a true passed pawn. Half bonus is given.

white a4 b5 against b6
b5 is a candidate, after the pawn sacrifice a4-a5. Half bonus is given.

**Comment by singaurav** [comment]
Thank you both for your responses. Looks like apart from name improvement, this is not an issue at all. Hence closing.
