### ISSUE TITLE
Follow-ups on cluster branch

### ISSUE THREAD

**Issue by noobpwnftw** [official-stockfish/Stockfish#1600]
Let's not forget this branch is not entirely a closed case.
I have done some study on the invalid PV move issue, it turns out to be the case when the "best thread" prints its PV, it does not have a consistent local TT to back it up.
So this is probably caused by the new cluster TT replacement policy, a remote TT injection may happen after local saves and overwrite them.
If that was the case, then it may be harmless since we can just filter out those invalid moves in a cosmetic way, essentially only the move that gets played matters.
Is there any other cases that can trigger this scenario in a harmful way?

**Comment by vondele** [comment]
also I would like the discussion on the cluster branch going. Can we get input from @omor1 on your finding ?

**Comment by noobpwnftw** [comment]
I have configured a 100-node MPI cluster running MPICH-3.2, compiled and deployed the https://github.com/official-stockfish/Stockfish/tree/cluster branch.

One obvious problem is that when I issue `go infinite` and then `stop`, multiple `bestmove` lines are outputted.

This can also happen with a 2 node cluster, by running with `mpirun -ppn 1`.

**Comment by noobpwnftw** [comment]
I have fixed the above problem in my recent PRs.

While I'm working on the issues, I figured that pondering does not work so far:
Nodes have their own ponder moves, one node gets to output its result, but `ponderhit` is not particularly handled differently on different nodes to ensure nodes work on the same position.

**Comment by omor1** [comment]
Sorry for not keeping up with this, I've been busy with other research and only now freed up a bit of time.

So with the invalid PV moves, this is because a TT entry has been replaced with a (better, assuming the replacement policy is correct) move from somewhere else, but the entry is still referenced from the PV? How does normal replacement handle such cases? I thought I was just using the same logic.

Some other issues could be because it (technically) violates the MPI spec. There is no guarantee that all processes can print to standard output or that output is ordered correctly. It would probably be best to instead send the information (or the string) to rank 0 (or whatever is returned for the `MPI_HOST` attribute on `MPI_COMM_WORLD`) and print it there.

**Comment by noobpwnftw** [comment]
I believe the invalid PV problem is solved, possible cause was multiple nodes outputting their lines and sync_cout doesn't really work across nodes in the MPI environment.

**Comment by omor1** [comment]
Ah, I thought those were two separate issues for some reason.

**Comment by rajb245** [comment]
I'm curious what the status is with this. If I want to play around with / help test cluster functionality, is  https://github.com/omor1/Stockfish/tree/cluster where I should start? Or cluster branch of official-stockfish/Stockfish?

**Comment by noobpwnftw** [comment]
Another TODO:
After https://github.com/official-stockfish/Stockfish/commit/67ae53b020cbc604a817d249933973fbc9de866b we have a new voting algorithm.

From that I have a new problem:
Do we let the nodes in the cluster cast the vote locally, then the nodes cast their bestThread vote on root(electoral votes), or we let all the threads in the cluster cast their votes on root?

**Comment by vondele** [comment]
@noobpwnftw  I've added a PR with the TODO (and an unrelated fix).

the easiest to implement would be the two level scheme, the best would presumably be if the results of all threads are dealt with globally. Presumably best done by globally reducing the map with the votes (rather than having all threads send their result around..the map is limited in size to the number of moves, the number of threads hopefully can scale).

**Comment by vondele** [comment]
BTW, I'm currently working on having the nodes counted properly, but it will take a few more days.
