### ISSUE TITLE
Stockfish's main weakness

### ISSUE THREAD

**Issue by Karlon** [official-stockfish/Stockfish#180]
I am an ardent admirer of Stockfish, and been using it since the day the very first version was released. Thoroughout the years, I have observed the great progress of Stockfish and it is truly remarkable to see it prosper. It is absolutely near-perfect in all areas of chess, but if there's one thing that makes Stockfish look like a 1200-elo rated chess engine, it's finding tactical or positional sacrifices in complex or simple positions. That's the main weakness, and I have seen many people report it but no progress have been seen so far on this. I believe there needs to be much attention paid on this.

Exposing the weakness:

PROBLEM 1:

8/1pN4r/5pkp/8/5K1p/2P4N/P3Bn2/8 w - - 0 1 

In this position, Stockfish fails to find a very simple Bh5+, even after 2 hours of analysis while Houdini, Critter and even Toga found it within some seconds. 

PROBLEM 2:

r1b2rk1/2q1bppp/pp2p3/2npP3/1n3P1P/2NBBN2/PPPQ2P1/1K1R3R w - - 0 14

Once again, Stockfish fails quite hard in finding an immensely simple Bxh7. And one more time, Houdini along with other weaker engines found this move easily. 

PROBLEM 3:

4rb2/1p1q1ppk/p1n1p2p/2p1Pn2/3PNR2/2P2K2/P2QBP2/6R1 w - - 0 1

This is complete horror for Stockfish, as it fails in both evaluation and finding the right move which is Rxf5. Stockfish thinks it's black who is winning, while quite clearly...White has a 6-move mate over black. 

PROBLEM 4 (the hardest one, also responsible for making Stockfish look like a chess beginner):

4q1kr/p6p/1prQPppB/4n3/4P3/2P5/PP2B2P/R5K1 w - - 0 24

Finding the right move, Qxe5 is impossible for Stockfish. It fails to find it, even after 24 hours of analysis. 

There are many other problems which Stockfish fails miserably in solving and these four are among of them. I hope the developers take a great look on this and focus on fixing this weakness.

**Comment by lucasart** [comment]
I understand your frustration, but this is a by-product of selective search. We optimize for elo, not for worst case scenario, nor for elo under constraints of worst case scenario. If you optimize for worst case scenario (tactical test suites), you will surely lose lots of elo. It's a very subtle tradeoff.

I'm sure I (or anyone who vaguely understands how the search works) can write a patch that "fixes" the "bugs" you mention, but the result will be an elo loss.

Anyway, this is a vague user requirement, not programming related, so I suggest we close this pull request, because I don't see how it can be useful. Instead you can post in the SF dev forum.

**Comment by mcostalba** [comment]
Non issue. Closed.

**Comment by Karlon** [comment]
Lucasart, can you give me that patch?
