### ISSUE TITLE
Change of the sent to the gui score

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#1868]
The Stockfish score is not at all aligned with the gui meaning, like other knowns engines.
Based on my tests, in my opinion, on the uci.cpp file, simply I propose to make this modification (not affecting the playing strenght):
ss << "cp " << v * 100 / PawnValueEg;
to
ss << "cp " << v * 70 / PawnValueEg;

**Comment by noobpwnftw** [comment]
Centipawn scoring has no meaning nevertheless, just people happen to agree that the measurement is based on a pawn's worth is roughly 100, as you quoted in its original form.

Changing it to any value that you see fit is simple because you can make the change and compile the code, but it also has no meaning to have it applied to everyone else.

**Comment by Chess13234** [comment]
@noobpwnftw the "GUI" may adjudicate "Resign at N centipawns" earlier in the 100 / PawnValueEg vs  70 / PawnValueEg;

**Comment by MichaelB7** [comment]
I agree with @noobpwnftw , just increase the N value to make it resign later or change the code for your own personal use.  There is no right or wrong answer - it is was the user decides.

**Comment by amchess** [comment]
In my opinion, the problem isn't the resign you can set via the gui but the coherence with the same gui (in cp) score. We know we can't change it and it's the following:
|score| < 25  =
25 < |score| < 70 light preference
70 < |score| < 140 preference
|score| > 140 decisive advantage

For example, if you launch, in infinite analysis and disactivated contempt, Stockfish, the score visualized by the gui is about 36 and to me it's too optimistic.
Other respectable engines, like komodo, are more precise and show 25.
In terms of Shashin's theory this seems to me more realistic: a Capablanca-Tal/Caos position for the turn advantage.
So, 25 * 100/36 is about 70. 
I know it's a very simple modification and for that very humbly I suggested it.

**Comment by ddugovic** [comment]
What is this "the GUI" which has the following properties (that requires changing this engine used on millions of devices)?

> We know we can't change it and it's the following:
|score| < 25 =
25 < |score| < 70 light preference
70 < |score| < 140 preference
|score| > 140 decisive advantage

**Comment by amchess** [comment]
Every known gui: Fritz, Arena, etc...

**Comment by ddugovic** [comment]
According to [Stack Exchange](https://chess.stackexchange.com/a/17255) "decisive advantage" threshold is 150 between engines, 200 between GMs, etc.

Using Stockfish evaluations, a regression was done which yielded a "winning chances" curve.  Perhaps a similar experiment could be conducted for other engines:
https://chesscomputer.tumblr.com/post/98632536555/using-the-stockfish-position-evaluation-score-to

**Comment by Rocky640** [comment]
Internally, we can continue to process our scores as we like.
However I like how Houdini publish the score for the gui:, it uses some "calibrated centipawns"

From chessbase:
`Houdini 4 uses calibrated evaluations in which engine scores correlate directly with the win expectancy in the position. A +1.00 pawn advantage gives a 80% chance of winning the game against an equal opponent at blitz time control. At +2.00 the engine will win 95% of the time, and at +3.00 about 99% of the time. If the advantage is +0.50, expect to win nearly 50% of the time.`

The winning chance curve published in the post just above is from 2014. one would have to repeat the experiment, and such result could be use to produce a calibrated output.

**Comment by amchess** [comment]
This is not the question at all.
I know there are these studies, but the problem still remain:
the incompatibility of Stockfish evaluation with gui's score.
I'm a IM correspondence chess player and I know a lot of strong players (also GM) who don't faith in Stockfish evaluation for this reason and don't use it in analysis.

**Comment by man4** [comment]
For what it's worth, I do think the current Stockfish evaluation is "inflated", in the sense that if you analyze the start position with odds, the evals are much higher in magnitude than you'd expect.
For example (I used low depths of around 20 so that the search doesn't dominate and find a position much better than the root):

b1-knight odds
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/R1BQKBNR w KQkq - 0 1
Eval: ~-4.6

a1-rook odds
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/1NBQKBNR w Kkq - 0 1
Eval: ~-6.4

queen odds
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNB1KBNR w KQkq - 0 1
Eval: ~-13.4

g2-pawn odds (I didn't want to cherrypick the worst pawn to remove, which is likely f2, so I picked one of the worse ones, keeping in mind that this is balanced by the fact that it's white to move)
rnbqkbnr/pppppppp/8/8/8/8/PPPPPP1P/RNBQKBNR w KQkq - 0 1
Eval ~-1.3

Normally you'd expect (as an approximation) -3 for knight odds at low depth, -5 for rook and -9 for queen, but these evals are higher by about 30-50%.

As it turns out, `PawnValueEg` used to be 258 a few months back; it is now 208, so the eval scale has been shifted up by ~25% in the last few months. Meanwhile, it's not clear that 208 is the true "average value of a pawn," because things like piece-square tables and bonuses can shift the average. (For example, one could decrease a piece value by 100 and increase the corresponding PSQT by 100 without affecting the true piece value.)

If people think this is an issue, one possibility that doesn't require periodically calibrating output vs. winrate is to use `v * 300 / KnightValueMg` or `v * 300 / KnightValueEg`, rather than `v * 100 / PawnValueEg` (or similar ideas). A look at the `git blame` history suggests that `KnightValueMg` has changed a lot less in percent terms than `PawnValueEg`, and this change would bring the piece odds evals more in line with what us humans might expect.

Of course, there are objections to this approach:
1) the choice of knight value is quite arbitrary. I have to admit this is true.
2) a "centipawn" is no longer 1/100 of a pawn. However, it wasn't previously either, because things like PSQT and pawn bonuses skew the "true" value of a pawn.

I just wanted to give this as a suggestion to keep the discussion going, because not only is adjudication affected, but also many people use Stockfish to analyze human games and would benefit from knowing that, for example, +1 does correspond to a pawn up on average.

**Comment by Vizvezdenec** [comment]
since when depth 20 is "low"?
It's enough to see that w/o knight white position is much worse than simply not having a knight :)

**Comment by man4** [comment]
> since when depth 20 is "low"?
> It's enough to see that w/o knight white position is much worse than simply not having a knight :)

It's "low" enough that the eval is quite stable around depth 15-25. It's enough to see that white has a much worse position by a knight, but that's about it. This is why I chose a quiet position rather than a tactical position.

But I realize an argument can still be made that depth 20 is not "low." Instead, let's look at the static evals instead of depth 20 evals:
b1-knight odds -4.01
a1-rook odds -5.91
queen odds -13.04
g2-pawn odds -0.89

So, it's true that these evals appear less inflated than before, but they're still inflated by 20-40%, and the point still stands. (For the g2-pawn, from benefit of hindsight, removal of g2 gives partial compensation by allowing immediate fianchettoing, so this wasn't a great example of a position worth -1.)

This is a reflection of the fact that the ratio `KnightValueEg/PawnValueEg` is currently about 4.16, when in reality a knight is closer to 3 pawns on average. One way to put this is that the PSQT and bonuses have a more positive effect on pawns than they do on knights (such must be the case in order to compensate the low `PawnValueMg` and `PawnValueEg`). A rough glance does suggest there are more bonuses than penalties for terms involving pawns.

**Comment by MichaelB7** [comment]
I’m not opposed to changing this - I would just hope that any changes are well thought out as I don’t believe the real solution is a simple multiple x by y. (Although if that is the solution , it would not bother me ).

**Comment by Vizvezdenec** [comment]
g2 pawn odds are -0.89.
This just means that sf thinks that in startposition knight = 4,5 pawns, rook = 6,5 pawns etc.
Actually it's what sf has as KnightValueMg/PawnValueMg and RookValueMg/PawnValueMg - in midgames sf thinks that knight >> 3 pawns, Rook >> 5 pawns etc.

**Comment by Hanamuke** [comment]
I agree with @Vizvezdenec , our pawn eval is "deflated" because this raw eval is a small part of pawn evaluation relatively to other pieces.  @man4 is also right that our evaluation features are not orthogonal, it would maybe be nice to change piece value/PSQT so that PSQTs average to 0. Unfortunately this is not a trivial change since we use pawn value in other places in the code.

**Comment by Hanamuke** [comment]
To get back to the discussion, I think that what should be done is to have a clearer correspondence between win rate and evaluation, maybe like Houdini does.
Also as a reminder, Stockfish was never designed to evaluate positions, but to find the best moves.

**Comment by Chess13234** [comment]
Score sent to "gui"(in this case cutechess-cli) has major implications since 
 fishtest early adjudication uses very shallow conditions for  adjudication for draw/loss, see issue https://github.com/official-stockfish/Stockfish/issues/1904

**Comment by ddugovic** [comment]
> Also as a reminder, Stockfish was never designed to evaluate positions, but to find the best moves.

What I'm curious about here is: if PSQT and pawn values were re-normalized to increase a pawn's value and reduce the bonuses (which I assume would be a functional change) and/or other pawn parameters, could Elo be gained?  Granted, these bonuses are already quite low, and this is a rather open-ended question, but still:

https://github.com/official-stockfish/Stockfish/blob/14c4a40dc7c4d6ddec6fb2447c2dac82aa590de2/src/psqt.cpp#L93-L102

https://github.com/official-stockfish/Stockfish/blob/14c4a40dc7c4d6ddec6fb2447c2dac82aa590de2/src/evaluate.cpp#L154-L173

**Comment by Hanamuke** [comment]
@ddugovic Following my comment I ha ddone the following tuning, but without success. Feel free to do it however you like though, I agree that there is probably elo to be gained.

http://tests.stockfishchess.org/tests/view/5c1cb6980ebc5902ba128ff2
http://tests.stockfishchess.org/tests/view/5c1d5fc60ebc5902ba12964e

(There was a first tuning in which i forgot to set the base engine to my tuning branch, and i took the output value for the secind tuning nonetheless, figurine it should be ok, if you want to redo it properly)
