### ISSUE TITLE
rand64()

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1903]
Could it possible against old slow xorshift with multiplication  to implement for zorbist and other with more fast and quality prng algo like:

http://xoshiro.di.unimi.it/xoshiro256plus.c

or

http://xoshiro.di.unimi.it/xoroshiro128plus.c

Acknowledgments:

http://xoshiro.di.unimi.it/

**Comment by noobpwnftw** [comment]
No.

**Comment by d3vv** [comment]
Why?

**Comment by d3vv** [comment]
All about http://www.pcg-random.org/posts/xoshiro-repeat-flaws.html ? )))

**Comment by d3vv** [comment]
But yo have to used prng from S Vigna
go to pcg,,

**Comment by noobpwnftw** [comment]
Because it makes no difference with Zorbist implementation or anywhere that uses it in SF.
1. We use it to build Zorbist random keys only at initialization in order not to have a big array of numbers written in code.
2. It used a fixed seed(IV) meaning that it is deterministic and the quality of randomness from RNG would have no meaning, we tested the resulting values to find a set with least hash collisions, then let the RNG produce them every time.
3. For our particular use pattern it would not render any measurable performance difference.

**Comment by d3vv** [comment]
Okey-dockey... But as for me SF has very long init
slightly delayed by zorbist, slightly delayed by calculate popcnt table and malloc for it, slightly delayed by other thing... GL

**Comment by d3vv** [comment]
My last question is - Why don't to use always most fast and quality algorithm in any cases?
