### ISSUE TITLE
Make tweak LTC [0, 3.5]

### ISSUE THREAD

**Issue by Alayan-stk-2** [official-stockfish/Stockfish#1919]
Right now, a code change adding complexity has looser requirements for LTC SPRT than a small tweak.

I think this doesn't make sense.

Green are rare enough that the resource difference is not a concern ; and for parameter tweaks we're more ok if the change is only a minor elo-gainer.

**Comment by vondele** [comment]
I agree that we should eventually move to [0, 3.5] for LTC parameter tweaks for consistency. 

The consideration to be made is testing cost. With STC [0,4] bounds, more expensive tests at LTC will result. This could be countered using [0.5, 4] for STC, but this would make parameter tweaks more difficult to pass, or [0.5, 3.5] STC (which would increase STC testing cost, with the benefit of yielding more precise elo estimates of tests).

**Comment by NKONSTANTAKIS** [comment]
My viewpoint is that STC confidence is of low quality, hence increasing STC costs is a bad investment.

On the topic, of course it does not make sense, but similarly it does not make sense to use equal bounds for code adders and tweaks. Tweaks are:

1. Harmless
2. Constantly changing optimal values as the engine changes

This means we will not suffer longterm by accepting some regressions, as we will not "marry" the values, and also that its good for us to retune the same values periodically.

So imo the proper strategy should be to use as few resources as possible and accept patches which will bring positive elo on average. I estimate that a target around 0.5 elo on average is good. 10 patches will net +5 elo. 

Of course if we overdo it with saving resources we will lose human-effort efficiency through the increased amount of written patches. So even if the optimal progress is a positive slope with big fluctuations (more regressions), its more convenient to us to use smaller. ie 0.5 +-1 instead of 0.5+-2.

@Alayan-stk-2 @vondele Which would be the bounds which would correlate to 0.5 +-1 ?
How about 0.8 +-1.5 or 1 +-1.5 ?

**Comment by mcostalba** [comment]
This is an important topic, but should be discussed with numbers. So eventually repoen with comparison tables out of @vondele tool.
