### ISSUE TITLE
Slowish start on the big core counts

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#1967]
Just witnessing pretty signifficant slowdown at start of the game at 4c which uses 90 cores and fast TC.
https://www.chess.com/computer-chess-championship
Click at any game/speed, sf at first move hovers between 1/4 and 1/2 of normal 90~ mnps there (sometimes for 1-2 moves extra). Also I've seen some graphs from people tests showing the same https://i.postimg.cc/GtY4vf3m/Screenshot-96.png and this thing is not existing in cfish/asmfish.

**Comment by JavaMast** [comment]
@Vizvezdenec  
In my case it is because of a big hash. Same thing happens in command prompt.

**bench 16384 8 15**

![screenshot_109](https://user-images.githubusercontent.com/42765009/51709855-91547700-2038-11e9-8314-03a1666e4685.png)
![screenshot_107](https://user-images.githubusercontent.com/42765009/51709872-9c0f0c00-2038-11e9-859e-0a0c22dbeebb.png)

In Aquarium GUI, Stockfish needs about 5-6 seconds  before start thinking.

===============
CPU  Ryzen 1700X

**Comment by JavaMast** [comment]
@CoffeeOne 
On my PC Large Pages is disabled in OS

**Comment by Vizvezdenec** [comment]
@CoffeeOne 4c uses linux.
Sf is still slowed down on 1st move there.

**Comment by d3vv** [comment]
and very slow random for hash, need xoshiro or  jenkins's prng )))
