### ISSUE TITLE
is_KQKRPs bug

### ISSUE THREAD

**Issue by elcabesa** [official-stockfish/Stockfish#1971]
this function definition too seems wrong
to match the definition it should be:

```
bool is_KQKRPs(const Position& pos, Color us) {
    return  !pos.count<PAWN>(us)
          && pos.non_pawn_material(us) == QueenValueMg
          && pos.count<QUEEN>(us) == 1
          && pos.count<PAWN>(us) == 0;
          && pos.non_pawn_material(~us) == RookValueMg
          && pos.count<ROOK>(~us) == 1
          && pos.count<PAWN>(~us) >= 1;
}
```

**Comment by Rocky640** [comment]
Your suggested change is equivalent to master

a) you add line `&& pos.count<PAWN>(us) == 0`   (i remove the semi-colon)
    but this is akready covered by the very first line !pos.count<PAWN>(us)

b) You also add  `&& pos.non_pawn_material(~us) == RookValueMg`
but this is handled with          ` && pos.count<ROOK>(~us) == 1`
it cannot harm, but is not really needed

c) for reference here is the master code
```
return  !pos.count<PAWN>(us)
          && pos.non_pawn_material(us) == QueenValueMg
          && pos.count<QUEEN>(us) == 1
          && pos.count<ROOK>(~us) == 1
          && pos.count<PAWN>(~us) >= 1;
```

I don't think we need the line  `&& pos.count<QUEEN>(us) == 1` in master.

**Comment by elcabesa** [comment]
a) you are right
b) pos.count<ROOK>(~us) == 1 is different from pos.non_pawn_material(~us) == RookValueMg
because pos.count<ROOK>(~us) == 1 is valid for position kq vs krnp ( but I don't know whether this case is handled externally at this position due to checking who is winning )

**Comment by Rocky640** [comment]
b) you are right. I edited my original post.

So  I agreeL we should change
```
return  !pos.count<PAWN>(us)
          && pos.non_pawn_material(us) == QueenValueMg
          && pos.count<QUEEN>(us) == 1
          && pos.count<ROOK>(~us) == 1
          && pos.count<PAWN>(~us) >= 1;
```

with
```
return  !pos.count<PAWN>(us)
          && pos.non_pawn_material(us) == QueenValueMg
          && pos.count<QUEEN>(us) == 1
          && pos.non_pawn_material(~us) == RookValueMg
          && pos.count<ROOK>(~us) == 1
          && pos.count<PAWN>(~us) >= 1;
```

or simply to
```
return      !pos.count<PAWN>(us)
          && pos.non_pawn_material(us) == QueenValueMg
          && pos.non_pawn_material(~us) == RookValueMg
          && pos.count<PAWN>(~us);
```

**Comment by Rocky640** [comment]
Some technical notes

it is important to know that scaling function (such as ScaleKQKRPs[c]) will apply only for the "strongSide"
which is computed here in evaluate.cpp line 327, is WHITE:
```
template<Tracing T>
  ScaleFactor Evaluation<T>::scale_factor(Value eg) const {

    Color strongSide = eg > VALUE_DRAW ? WHITE : BLACK;
    int sf = me->scale_factor(pos, strongSide);

```

"eg" is the endgame value extracted from the score computed by evaluation, and contains the material scores as well.

Our current eg values for pieces
PawnValueEg   = 208, KnightValueEg = 865, BishopValueEg = 918, RookValueEg   = 1378,
QueenValueEg  = 2687,

 if we look at the material sum only

**a)** According to master, White (with KQ) will most likely be the "strongside" against the following black configurations 
 
Rp,  Rpp,  Rppp, Rpppp, Rppppp = 2416,    

**b)** Also against these
RBp =2504  RNp = 2451

**c)** For the following cases, the "strongSide" is not so clear and will depend on other evaluation factors
RNpp = 2659  RBpp = 2712 Rpppppp = 2626 or other Rp's case with some advanced passed pawns.

**d)** Otherwise if black has more minors or more pawns, he is quite likely the "strongside", and the scaling factor will not apply 

Now: for any case a, b and c, is_KQKRPs is true. But only when white is the strongside (a) b) and some c))
the following will be computed by master
`ScaleFactor Endgame<KQKRPs>::operator()(const Position& pos) const {``
which produce either a SCALE_FACTOR_NONE (and no special scaling is applied) 
or a SCALE_FACTOR_DRAW =0 (if black has some KRP fortress - like position).

Master correctly assume that having an extra minor or pawn(s) cannot harm the fortress
By keeping the fortress material, in worst case, we can give the extra material away, and still draw.

for **a)** however, shouldn't BLACK be (most of the time) the strongside with KQvKRpppp or more pawns ? For this, some imbalance could be hard coded. This case is too rare however to be measured on fishtest and unfortunately, we do not have 8 men tablebases. For KQvKRppp, see some stats further below.

for **b)** and some **c)** **where black has one minor**, something funny happens: we also compute the following in material.cpp line 201
    
```
if (!pos.count<PAWN>(WHITE) && npm_w - npm_b <= BishopValueMg)
      e->factor[WHITE] = uint8_t(npm_w <  RookValueMg   ? SCALE_FACTOR_DRAW :
                                 npm_b <= BishopValueMg ? 4 : 14);


```
so e->factor[WHITE] will be 4
and at the end of the day, because of material.h line 55
`return sf != SCALE_FACTOR_NONE ? sf : ScaleFactor(factor[c]);`

the applied scale factor will be either 0 (black has a fortress) or factor[c]=4 (black has no fortress)

In view of the following statistics taken from https://syzygy-tables.info where we see that all 3 outcomes are possible for the KQvKNp or KQvKBp cases, and white expectation is near 50%, my guess is that this "4" is too low. Again, it will be impossible to measure this on fishtest.

![image](https://user-images.githubusercontent.com/8949638/51792744-c5887e80-2183-11e9-9d63-65cf59f6e710.png)


Conclusion:

IMHO, there is no bug, but the case KQvKRBp or KQvKRNp is quite convoluted with this unexpected scale factor 4 which seems to appear from nowhere (but which might be correct !)

Detecting a draw is certainly useful in the KQvKRp and KQvKRpp cases
since black is not the clear favorite, and saving (or avoiding) a draw when possible is great. 

It is not clear at all if we need to change master for other cases where is_KQKRPs is true
This would require external testing similar to recent KNBvK.
