### ISSUE TITLE
Interesting discovery

### ISSUE THREAD

**Issue by jhellis3** [official-stockfish/Stockfish#2036]
Was doing some coding on a derivative and noticed a triggered assert relating to line 1203 of search.

Tracked that to value > -VALUE_INFINITE.

Tracked that to singular extension search, where singularBeta is set to `std::max(ttValue - 2 * depth / ONE_PLY, -VALUE_MATE);`  Then the singular extension search with an excluded move can have alpha = -VALUE_INFINITE, when singularBeta == -VALUE_MATE since -VALUE_INFINITE == -VALUE_MATE - 1.   Or -32001, -32000.

In any event, on line 1171, we do this: `    if (!moveCount)
        bestValue = excludedMove ? alpha
                   :     inCheck ? mated_in(ss->ply) : VALUE_DRAW;`

In the rare case that SingularBeta was set to -VALUE_MATE, and alpha is thus -VALUE_INFINITE, we can set bestValue to -VALUE_INFINITE thus triggering the assert on line 1203.

Anyway, just thought I would mention it...

**Comment by joergoster** [comment]
Good catch!
A real corner case which was introduced by this patch: https://github.com/official-stockfish/Stockfish/commit/351844061eddffac59e7a3c2d16af7ea9661bb3e

The simplest fix seems to be
          Value singularBeta = std::max(ttValue - 2 * depth / ONE_PLY, -VALUE_MATE + 1);

**Comment by mcostalba** [comment]
@jhellis3 @joergoster thanks for reporting and analyzing this!

Indeed 351844061edd was introduced to **slightly** improve mate finding in (quite artificial) conditions, like 1 sec or even 200K nodes per position, and was tested as a simplification (that is not btw).

I see that with a further tweak -VALUE_MATE + 1 we eventually fix it, but an even easier fix is to just revert 351844061edd. This would let the code simpler IMO.

Just this morning I went through search.cpp for some triviality/formatting and I was impressed by the number of obscure/complex stuff that we have accumulated there over time. It was a while I was not reading it and I admit that I didn't recognized many parts of the code: it got **much** more complex than what it used to be just a couple of years ago. Many of these complexities are not easy to remove/simplify without losing ELO, but where we can simplify search.cpp I am all for it because it is the basic file of the engine (together with evaluation.cpp) and, as it is today, it is very difficult to read.

So in this case, @joergoster , if you don't mind, I would revert the patch instead of logically complicating it even further. With logically complicating I mean that people have difficulty to understand what that -VALUE_MATE + 1 stands for.

**Comment by joergoster** [comment]
@mcostalba Reverting is perfectly fine for me. Will you do it, or do you want me to open a PR?

**Comment by mcostalba** [comment]
@joergoster thanks. No problem, I will do it myself.

**Comment by mcostalba** [comment]
Reverted in 4d0981fef37c85edfd7a0.
