### ISSUE TITLE
Scale value draw, contempt and eval

### ISSUE THREAD

**Issue by Alayan-stk-2** [official-stockfish/Stockfish#2052]
Endgame scaling functions are used among other things for situations where we know some forced draws but otherwise use the regular evaluation.

I think current SF behavior could be improved in two ways : 
- If a draw is detected, return a pure draw eval (0.00) rather than letting contempt be applied on top. This is mostly cosmetic.
- If a draw is detected, skip the regular eval altogether for this position as the computations are wasted.

That is, we'd want to have the same behavior than with endgame eval function when the result is a known draw, but otherwise run the regular eval.

Thoughts ?

**Comment by ddugovic** [comment]
I'm not sure what you mean by:

* If a draw is detected, skip the regular eval altogether for this position as the computations are wasted.

I disagree with the former because evaluation is used to rank moves; returning 0 would negate the entire effect of contempt (Stockfish would no longer prefer the non-drawing move).

**Comment by Alayan-stk-2** [comment]
> I'm not sure what you mean by:
> 
>     * If a draw is detected, skip the regular eval altogether for this position as the computations are wasted.

Computing regular eval, then multiplying it by zero means that the output of the regular eval is wasted. Some more nodes could be explored otherwise.
 
> I disagree with the former because evaluation is used to rank moves; returning 0 would negate the entire effect of contempt (Stockfish would no longer prefer the non-drawing move).

What ?

SCALE_VALUE_DRAW is used for known fortress draws in material configurations which, otherwise, have good winning chances. There is no "non-drawing move" (besides losing suicidal moves) in these fortresses.

Now some moves might be better than other to swindle out a win against bad opponents, but having all moves ranked at 0.13 instead of 0.00 doesn't help at all for this (and SF is not tuned to swindle much weaker opponents anyway).

**Comment by ddugovic** [comment]
I see; I hadn't considered the possibility that non-best play (moves which have a negative evaluation exceeding the contempt threshold) could risk losing the game.

Indeed, short-circuit evaluation could improve performance (affording CPU time to explore other nodes) if branch prediction (speculative execution) is accurate.  I'm curious whether link-time optimization could yield further improvements (without changing code complexity).

I thought `SCALE_VALUE_DRAW` was used for material configurations which normally are fortress draws but in rare cases a forced win could exist (since actual fortress detection is a hard problem).

**Comment by Alayan-stk-2** [comment]
> Indeed, short-circuit evaluation could improve performance (affording CPU time to explore other nodes)
Yes that's the idea, though I expect the benefit would usually be small.

> I thought `SCALE_VALUE_DRAW` was used for material configurations which normally are fortress draws but in rare cases a forced win could exist (since actual fortress detection is a hard problem).

Usually, these material configurations have many winning positions but also many drawn ones. Most scaling functions don't try to evaluate all possible one as won or drawn ; rather they identify a subset which match a simple draw pattern and apply SCALE_VALUE_DRAW ; while applying no scaling at all if the conditions aren't met.

As far as I can tell, either the conditions guarantee the draw, or the exceptions are 1)rare ; 2)the winning side can easily force out of the conditions in a few moves thus limiting impact of false positives.
