### ISSUE TITLE
Possible memory leak with syzygy

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#226]
As reported here:

http://talkchess.com/forum/viewtopic.php?t=55010&postdays=0&postorder=asc&topic_view=&start=10

"What I mentioned about the POPCNT version not having memory leak is incorrect. Out of the box there is no problem, but if you set the syzygy path for the engine the leak will become obvious in infinite analysis. The inclusion of syzygy seems to be the cause. I downloaded the release candidate stockfish_15011815_x64_modern.exe for this test."

To be confirmed.

**Comment by zamar** [comment]
I think that there is a serious misunderstanding in that thread. Growing memory use is not a proof of memory leak.

Syzygy memory maps files into RAM. In infinite analysis mode, more and more positions are accessed, which means that more and more files are stored in RAM. However OS is responsible of managing the allocation/deallocation of this memory rather than software.

But I guess some valgrind runs are required, to verify that there is no leak.

**Comment by mcostalba** [comment]
Yes, this makes sense. Actually the post author already hinted that this
_could_ be an expected behavior, nevertheless a valgrind session is due
IMO, sooner or later.

**Comment by glinscott** [comment]
```
===========================
Total time (ms) : 136797
Nodes searched  : 7849910
Nodes/second    : 57383
==26573== 
==26573== HEAP SUMMARY:
==26573==     in use at exit: 662,522 bytes in 289 blocks
==26573==   total heap usage: 140,120 allocs, 139,831 frees, 27,297,464 bytes allocated
==26573== 
==26573== LEAK SUMMARY:
==26573==    definitely lost: 0 bytes in 0 blocks
==26573==    indirectly lost: 0 bytes in 0 blocks
==26573==      possibly lost: 0 bytes in 0 blocks
==26573==    still reachable: 662,522 bytes in 289 blocks
==26573==         suppressed: 0 bytes in 0 blocks
==26573== Rerun with --leak-check=full to see details of leaked memory
```

**Comment by glinscott** [comment]
Valgrind run with 5-man TB on linux looks clean.

**Comment by mcostalba** [comment]
Thanks Gary, so the memleak is actually OS grabbing memory due to
mem-mapped TB.

I close the issue.
