### ISSUE TITLE
Stockfish Crashing

### ISSUE THREAD

**Issue by Shalarian** [official-stockfish/Stockfish#2261]
I run all day analysis, using 32GB of 64, 9980XE.  What is happening is when depth gets up around 80 (simpler positions--endgames) I get a memory crash.  BSDeath.   I think it happens when memory is "full".  I never have this issue on my other machines, though they are 4770k.
Am I missing a parameter or something?
Thanks

Using CB15, thumb drive tablebases from CB.  Win 10 Home,

**Comment by Kingdefender** [comment]
I don't think this is the right place for such questions, because unless there is information to the contrary, it is not so likely that it has much to do with Stockfish code itself? I would suggest asking advice from people with similar hardware, post the problem in [TalkChess](http://www.talkchess.com/forum3/viewforum.php?f=2) or Fishcooking for instance. Include relevant information, like the Windows error code on the blue screen. BSD is more likely indication of problems with your hardware, as I am sure you are aware of. Sorry if this does not help you.

**Comment by snicolet** [comment]
Discussion should be moved to the TalkChess or FishCooking forum, closing.
