### ISSUE TITLE
how do I adjust the strength?

### ISSUE THREAD

**Issue by yuribudilov** [official-stockfish/Stockfish#2271]
Hello.
I need help configuring the play strength of StockFish 10.
I can see that StockFish 10 has a few play strength related UCI parameters. 
I am not able to find any documentation and examples of what the actual values I can pass and how do I pass them?
I am trying to use StockFish 10 Windows 10 64-bit exe from either Arena 3.5.1 GUI (latest) or from PyChess GUI. I need to know how to pass engine arguments to make it limit its strength/ELO etc.
Without those arguments the engine is useless to me because on its maximum strength I am not able to play it.

For example, how do I get it to play at strength ~2000 ELO on Intel i7 CPU with 4 cores?

Many thanks in advance!

**Comment by Rocky640** [comment]
First, this is not the place to ask how to configure your GUI.
This is more for technical problems related to engine.

However you can use the fishcooking forum for such questions.
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking 

Anyway, here is some help:

Once you have loaded your Stockfish in Arena as your "Engine 1"
use the menu **Engines**, sub menu **Engine 1**, and sub menu **Configure**
from there you can change the skill level.

By default it is 20. You might want to try 5 or 6, which is close to 2000 ELO for engines as rated on CCRL https://ccrl.chessdom.com/ccrl/4040/rating_list_all.html

You will certainly find a suitable level after a few experiments.

As a side note, you can't really compare engines ELO to human (FIDE) ELO, since ELO is a relative measure which depends on the pool of players, and different rating authorities might use different computation rules.
For example, your own chess rating on Lichess or on Chess24 are probably different.
On CCRL, they uses BayesElo.
