### ISSUE TITLE
Is uiThread required to avoid data races?

### ISSUE THREAD

**Issue by niklasf** [official-stockfish/Stockfish#2299]
Apologies if #1990 was closed intentionally. If so, I'd appreciate brief explanantion.

---

`uiThread` is used here (a):

https://github.com/official-stockfish/Stockfish/blob/651450023619ddea590f301f040286151004df66/src/uci.cpp#L196

But not here (b):

https://github.com/official-stockfish/Stockfish/blob/651450023619ddea590f301f040286151004df66/src/uci.cpp#L70

This means that there's either a data race in (b), or an upportunity to simplify away `uiThread` in (a). (Or a third option, that I am missing). Can anyone figure out which it is?

**Comment by vondele** [comment]
the rationale for uiThread is in the commit message 750dfa0521472e86c67f870fe7ca413d670cafe2 . If I understand correctly to allow certain commands while search is going on. That's a bit of a grey area, since UCI suggests that this is not conforming. So, the one at line 196 would be a feature, while the one at line 70 is OK for conforming uci commands. This is tricky code, I would recommend to compile with the sanitize=thread option, and see what happens when issuing UCI commands during search.

**Comment by xoto10** [comment]
@niklasf 
The comment vondele refers to says the problem is a data race if eval is requested while searching. It seems to me we could just deny this eval request, e.g. see my branch [uithread2](https://github.com/official-stockfish/Stockfish/compare/master...xoto10:uithread2)

**Comment by vondele** [comment]
yes, I did a quick check, and even with this uiThread in place, things are not race free issuing an eval during an ongoing search. It might have been a partial fix, but not the full fix. In that case, it is not clear if there is any benefit from the code.

**Comment by vondele** [comment]
this issue can be closed now.

**Comment by ddugovic** [comment]
@niklasf Merged to our fork at https://travis-ci.org/ddugovic/Stockfish/builds/600211626

**Comment by niklasf** [comment]
Thanks all.
