### ISSUE TITLE
uci parameters stockfish

### ISSUE THREAD

**Issue by kandalto** [official-stockfish/Stockfish#2490]
Hello,

Changing uci parameters with: 

**setoption name <option-name> value <option-value>**

does not appear to have any effect. I do not receive any errors, but upon typing **uci** I still get all the default parameters.

In particular I am trying with 

**setoption name threads value 6**

but I also tried different values and parameters.

**Comment by snicolet** [comment]
As long as you do not receive a `No such option: ...` error message when typing a `setoption name value` command, you can assume that Stockfish has received and recorded the change.

It is true that we don't output the current values of options after the `uci` command, but that is because it is not in the UCI protocol to do so.

You can change line 105 of ucioption.cpp by adding this line before thre break : 

```
   os << " current " << o.currentValue;
```

This will make a custom (not UCI compliant) version which allow you to check that the internal values of options change.
