### ISSUE TITLE
It is not possible to build with the latest sources (bench 4247490). MSVC 2017

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2659]
![Capture](https://user-images.githubusercontent.com/51216501/80872904-971a1d00-8cbd-11ea-81df-00dca77b1d42.PNG)

**Comment by vondele** [comment]
somewhat surprising since our CI testing is seemingly using MSVC 2017 as well, and it passes: https://ci.appveyor.com/project/mcostalba/stockfish/builds/32603317/job/xcq3anv1dharq9ww 

so we'll need to figure out where it goes wrong. I'm not sure if any of the devs use MSVC, so you might need to do some testing yourself. Can you try two things:
* Make sure your project files are up-to-date (i.e. the Makefile changed, you need to include the new tune.o when linking)
* Make sure you do 'make clean' or equivalent in your source tree
* If those two steps fail, the only special thing I can see about read_results() in tune.cpp is that it is an empty function. Try adding some code in the function, for example, `volatile int i = 0; i++;`near line 144 of tune.cpp.

**Comment by Marat-Ka** [comment]
Good job, vondele, thanks!
I do not use GitHub mechanisms to sync versions. I just copied all the files from the archive https://github.com/official-stockfish/Stockfish/archive/master.zip with the replacement files in my project
Therefore, tune.cpp and tune.h were not automatically added to the project. I added them manually, and the project was assembled.

Thank!
