### ISSUE TITLE
gcc  4.9.3 problem

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2665]
```
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -flto   -c -o misc.o misc.cpp
misc.cpp: In function ‘void* aligned_ttmem_alloc(size_t, void*&)’:
misc.cpp:306:38: error: ‘aligned_alloc’ was not declared in this scope
   mem = aligned_alloc(alignment, size);
```

**Comment by vondele** [comment]
https://gcc.gnu.org/develop.html#timeline so that's a rather old gcc (first released 2014). But it might actually be a feature of your glibc and/or OS, where we expect that function to be available via stdlib.h :
https://linux.die.net/man/3/aligned_alloc
I think we had some discussion on this when this feature was merged.

The easiest standard conforming way would be to upgrade to c++17 .... but that doesn't help gcc 4.9.3 either. 

Do you have a suggestion how this could be fixed (basically, I think we need an additional condition on the define that uses the code).

**Comment by d3vv** [comment]
Just I have glibc-2.15, and 

`The function aligned_alloc() was added to glibc in version 2.16`

Many legacy servers can't be upgraded 
And as for me I have used `posix_memalign()` for cross platform compatibility as well..

**Comment by vondele** [comment]
so on your system, can you test if the code works with posix_memalign ? 

I wonder if there are linux systems where aligned_alloc works but not posix_memalign.

**Comment by d3vv** [comment]
@vondele yes, it works for me:

```
misc.cpp: In function ‘void* aligned_ttmem_alloc(size_t, void*&)’:
misc.cpp:306:40: warning: ignoring return value of ‘int posix_memalign(void**, size_t, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   posix_memalign(&mem, alignment, size); //mem = aligned_alloc(alignment, size);
```

Have the same bench:

`Nodes searched  : 5185517`
