### ISSUE TITLE
Evaluation of closed positions

### ISSUE THREAD

**Issue by dorzechowski** [official-stockfish/Stockfish#2716]
Not an issue, this is meant as a better place to continue the discussion started in PR #2712.  It now looks like evaluation terms that bring Elo in tests with book closedpos.epd may at the same time lose Elo with standard book and thus be never commited to master. So the question is how to handle it in order to improve play in all types of positions and not discard good patches.

**Comment by vdbergh** [comment]
One needs to be careful though in drawing conclusions.

A failed non-regression test is not evidence for an Elo loss as a neutral patch has a relatively high probability of failing (it used to be 36%, I haven't checked recently).

**Comment by NKONSTANTAKIS** [comment]
From a chess-related perspective, it is natural that the advance of h-pawn is weakening K-side with open center, while much safer with closed. Furthermore closed center begs for gaining space at the flanks, and typically Black and White advance at opposite flanks. The advance which happens at the side where the enemy King lies is considered advantageous. Even if it does not result in mate, the suppressed King will have trouble getting endgame activity.

**Comment by xoto10** [comment]
The test process determines the strengths and weaknesses of the resulting engine.

My thinking is that testing with different books introduces complication into the process. A way to avoid this is to simply use one book all the time, but update it over time (e.g. every 3 months?) to address whatever the current priority is.

The feedback generated by successful / unsuccessful tests will gradually work to improve the weak points identified. So I would just use closedpos for the main testing book, or at least some blend of closedpos and the current main test book. If sf is weak somewhere, it means fishtest needs to emphasise that area more.

This has relevance to the fishcooking thread about protonspring's internal book test. Closed positions are reached at least some of the time with the current fishtest book, but **decisions on move 1, 2 or 3 are not tested at all**. Not surprisingly, sf consistently makes mistakes on moves 1-3, and shows no signs of improving. How would it improve when we don't test that ability, when we don't provide any feedback on that ability? So the regular opening book should include 0/1/2/3/4/5 ply openings as well as 6.

If it were my choice, I would create a new opening book with 1/3 positions from current test book, 1/3 positions from closedpos, 1/3 positions 0-5 plies from startpos on major opening lines. Obviously this might include lots of duplication to get these ratios. So be it. If this wasn't enough to address the problem in 3/6/12 months, then we could go to 50/50 closedpos openings and shorter ply openings.

**Comment by vondele** [comment]
just a note on the 1-3 ply openings... Decisions on which move to take depend on positions seen at least 10-20ply deeper, so I doubt somewhat our 6ply book is too deep.

Practically, in a book of 150k positions, the fraction of positions that can be, say 3 or 4 ply will be very small (perft 3 is 8902, perft 4 is 197281).

The popularpos book tried to address this by having a new balance (including short, and deep lines, closed and open), but didn't have the same Elo resolution as the noob_3moves.

**Comment by Alayan-stk-2** [comment]
Including a lot of positions close to startpos is terrible for diversity. The only sensible way to make this work would be to include near-opening chess960 positions, as one could get thousands of meaningfully different 1-5 plies positions. I'm not convinced the short book is the primary reason for SF opening issues, though. Incorrect evaluation deeper into lines (a lot of positions in the french are vastly overestimated by SF for black, for example) seems more fundamental.

As for closed positions in general, SF won't try to go for them because it has no reason to value them more from its eval and patches that make it go for those wouldn't bring fishtest elo most likely. One workable trick would be to include an extra parameter in SF that would act in a similar way to contempt but would value getting a more closed position. The default value for releases would do nothing, but in fishtest we'd set it to a mild preference for closed positions to ensure they are encountered more frequently. From then, patches that improve play in closed positions would have higher chances of successes.

**Comment by dorzechowski** [comment]
Topic looks dead, also in view of upcoming NNUE merge it will most likely be moot. Closing.
