### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by rapgro** [official-stockfish/Stockfish#272]
Please provide support for cmake. Attached a sample CMakeLists.txt as used currently in Fedora.

```
cmake_minimum_required (VERSION 2.6)
project (Stockfish)

set(EXE stockfish)

include_directories(${PROJECT_SOURCE_DIR}/syzygy)

aux_source_directory(. SOURCES)

add_executable(${EXE} ${SOURCES} syzygy/tbprobe.cpp)

target_link_libraries(${EXE} -lpthread)
```

**Comment by mcostalba** [comment]
Not an issue. Closed.

**Comment by jubalh** [comment]
@rapgro  What would be the gains of switching to cmake from the existing make?

**Comment by rapgro** [comment]
@jubalh Please compare complexity of my proposed CMakeLists.txt file above and the internals of a manually written Makefile. CMake does generate Makefiles and cares about automated configuration.

**Comment by tristntran** [comment]
Sorry for the post necromancy, but I think that we should reconsider cmakes. It seems like cmake has become the new standard for builders and software like CLion heavily favors it for debugging as makefile does not play nice with their gdb and runtime configurations. In order to grow and pass knowledge onto more contemporary programmers, we should consider updating our tools as well.

**Comment by bftjoe** [comment]
Considering the maintainers didn't even want to commit to integrating cmake  support when someone was willing to do all the work, good luck with that.

https://github.com/official-stockfish/Stockfish/pull/3012

**Comment by ppigazzini** [comment]
> Considering the maintainers didn't even want to commit to integrating cmake support when someone was willing to and did do all the work, good luck with that.

My opinion after reading that thread:
- the maintainers were interested to cmake:
https://github.com/official-stockfish/Stockfish/pull/3012#issuecomment-674715635
- the contributor never completed the work
- that fork mixed 2 things: adding cmake and making a static library

**Comment by bftjoe** [comment]
I suppose if you call full cmake support including PGO "unfinished", then
sure.

**Comment by ppigazzini** [comment]
You are free to suppose whatever you want.

That PR is "unfinished" because:
 - the first post has a list of open point to be implemented
 - the contributor never completed the work
 
The maintainers seems to be interested to switch to cmake so, if you are a cmake expert and you are sure that that code is ready, please open a PR.

**Comment by bftjoe** [comment]
Really? Because it was asked and no real interest in merging was shown.

**Comment by ppigazzini** [comment]
Please stop hand waving and write here the technical open points to have cmake in Stockfish, just to be sure that you understand that PR and the topic.

**Comment by bftjoe** [comment]
> I never got a clear answer on if people were really interested enough in this. I can update it easy enough since there are no changes to the code itself, but keeping on top of the frequent updates to Stockfish requires some effort.

> If the devs are willing and ready to accept a switch to CMake, I will update this. If not, I'll leave this fork up in case someone wants to use it as a reference someday.

**Comment by vondele** [comment]
https://github.com/official-stockfish/Stockfish/pull/3012#issuecomment-674715635

as said, it would be important that the current functionality is available. I.e. passes our CI, and works for the various crosses I regularly test. Once we have such a working example, we can judge if it makes the maintenance of the code base easier.

**Comment by bftjoe** [comment]
Even the basic cmake file that the travis ci auto generated let you open
the directory as a project in Visual Studio, it is very clear what the SF
devs position is when they didn't even commit that file.

**Comment by vondele** [comment]
you mean having multiple build systems is a good idea? I disagree with that, would rather prefer to have one build system, to maintain, extend, debug, etc... and yes, we can't support every tool chain/IDE out there.

**Comment by ppigazzini** [comment]
And please, remember that the switch to cmake can be done only after updating fishtest.

**Comment by winapiadmin** [comment]
They would cause some kind of problems with fishtest on Windows, e.g. using LLVM for Windows while running fishtest.

Fishtest also don't run on MSYS2/MINGW64 terminals (PR https://github.com/official-stockfish/fishtest/pull/2311) due to OS detection (https://github.com/official-stockfish/fishtest/issues/126#issuecomment-354744305) if configured improperly, but... who reads the wiki for windows installation

Also, LLVM is just clang/clang++, which Stockfish supports (except if you build with VS headers or use clang-cl)
