### ISSUE TITLE
No Pondering while in book.

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#2738]
I noticed during a tournament, that as long Stockfish is in book  (this was a bring your "own" book tournament), it does not analyze - even with pondering on.  The CPUs are not running at all. 

Would it make sense to have Stockfish to start analyzing while in book, and have it start filling it's hash table so that it gets a head start.  It seemed to me we're wasting  CPU cycles by not doing anything with the CPUs while in book.  I know the TCEC tournaments are not structured that way - so this can wait until that completes.

Thanks.

**Comment by nguyenpham** [comment]
IMO, that is good for SF vs human but may gain almost nothing for an engines' game since SF does not have books itself but depends on chess GUI's books. That means if SF is in a book, the rival is in that book too (usually the game starts from a given opening position). Thus no time for pondering for either side.

**Comment by nguyenpham** [comment]
I don't think we can do anything about that idea. SF is a UCI engine - stateless and works under chess GUI controlling. It means it can't start pondering if the chess GUI does not tell it to do. However, the dilemma is that when the rival starting for its first computing, SF does not start computing yet and the GUI has no information about the pondering move of SF, thus the GUI can't order SF to start pondering.

**Comment by MichaelB7** [comment]
Good point.   Will close.
