### ISSUE TITLE
computation of legality of en-passant move when king is in check

### ISSUE THREAD

**Issue by siemanko** [official-stockfish/Stockfish#2784]
I was comparing stockfish to python-chess and found some subtleties in the way en-passant moves are considered. From what I can tell stockfish does its best to only mark `ep_square` when there is a legal en-passant capture, but ignores the case when the king is in check prevents en-passant from being possible. I am very new to this codebase so it is hard for me to tell - is this a conscious design choice or a bug (if the latter, I _think_ it's on master too, but I only read the code and didn't run it to confirm).

**REPRO**
stockfish version `sf_11`

moves: 
```python
['b1c3', 'e7e6', 'g2g3', 'f8d6', 'h2h3', 'e6e5', 'c3a4', 'f7f5', 'a1b1', 'a7a5', 'd2d3', 'd6a3', 'c1d2', 'e8e7', 'd2c3', 'a3b4', 'c3b4', 'd7d6', 'b2b3', 'b8d7', 'd3d4', 'd7c5', 'a4b6', 'h7h6', 'b6d5', 'e7f8', 'g3g4', 'c7c6', 'b4a3', 'h8h7', 'b3b4', 'h7h8', 'g4g5', 'd8b6', 'f2f3', 'h8h7', 'd5f6', 'b6c7', 'd4c5', 'c7b8', 'f6e8', 'h6h5', 'e1f2', 'f8f7', 'e8f6', 'f5f4', 'f6d5', 'a5a4', 'f2e1', 'h5h4', 'b4b5', 'b7b6', 'b1b4', 'c8g4', 'd5c7', 'g8e7', 'c7e6', 'e7g8', 'h1h2', 'h7h6', 'e6d8', 'f7e7', 'd1d6', 'b8d6', 'h3g4', 'a8a7', 'a3b2', 'd6c5', 'b2c3', 'c5b4', 'c3b4', 'h6d6', 'b4d6', 'e7d6', 'c2c4', 'd6c5', 'e1d2', 'h4h3', 'd8c6', 'g8e7', 'd2c1', 'e7c8', 'c6d4', 'e5d4', 'h2h1', 'c5c4', 'e2e4']
```

python-chess outputs fen: 
`2n5/r5p1/1p6/1P4P1/p1kpPpP1/5P1p/P7/2K2BNR b - - 0 44`
stockfish outputs fen:
`2n5/r5p1/1p6/1P4P1/p1kpPpP1/5P1p/P7/2K2BNR b - e3 0 44`

EDIT: Just checked that legal move generator is correct, so this probably just affects the way fen is printed.
EDIT2: This also happens when en-passant move would put the king in check.

**Comment by MichaelB7** [comment]
Your question is regarding Forsyth–Edwards Notation (FEN)  notation.

https://www.chessprogramming.org/Forsyth-Edwards_Notation

The en passant target square is specified after a double push of a pawn, no matter whether an en passant capture is legal or not.  It does not matter if the move is possible or not, it is simply identifying the en passant square after double square push of pawn.  It appears that the python-chess authors are not aware of this little tidbit.

**Comment by Rocky640** [comment]
There are many cases not covered in our code when we read a position fen

in position.cpp we can read the following comment
```
   4) En passant target square (in algebraic notation). If there's no en passant
      target square, this is "-". If a pawn has just made a 2-square move, this
      is the position "behind" the pawn. This is recorded only if there is a pawn
      in position to make an en passant capture, and if there really is a pawn
      that might have advanced two squares.
```

in view of previous comment, we are missing a few obvious cases:

for example, if white to move, and the ep square is e3, 
fen was clearly wrong, and ep should be disarded

for example, if white to move, and the ep square is f6, but f6 is occupied by a pawn, 
fen was clearly wrong and should be discarded

for example, if white to move, and the ep square is f6, but f5 is occupied by some piece, 
fen was clearly wrong and should be discarded

in an ideal world, fen are always legal and valid, but this is not a perfect world.
therefore, I think the following would be better code in position.cpp around line 256

```
 // 4. En passant square. Ignore if invalid.
bool enpassant = false;
  
  if (   ((ss >> col) && (col >= 'a' && col <= 'h'))
      && ((ss >> row) && (row == (sideToMove == WHITE ? '6' : '3'))))
  {
      st->epSquare = make_square(File(col - 'a'), Rank(row - '1'));
      
      // En passant is possible only if
      // a) side to move can "capture" with a pawn on epSquare
      // b) there is an enemy pawn in front of epSquare
      // c) there is no piece on epSquare or behind epSquare
      enpassant = 
          pawn_attacks_bb(~sideToMove, st->epSquare) & pieces(sideToMove, PAWN)
      && (pieces(~sideToMove, PAWN) & (st->epSquare + pawn_push(~sideToMove)))
      && !(pieces() & (st->epSquare | (st->epSquare + pawn_push(sideToMove))));
     // sync_cout << enpassant << sync_endl;
  }
  
  if (!enpassant)
      st->epSquare = SQ_NONE;
```

only case missing in above code would be to detect
d) if capture must not leave own king in check

If interested I can provide this too.
For example, White Ke1 e5 Black Re8 f6  ep square f6
white cannot play exf6 e.p because that would leave his king in check.

All this would ensure that when SF only set his internal e.p.square correctly,
and therefore output valid fen when debugging positions.
This might also avoids a few subtle bugs.

**Comment by Rocky640** [comment]
if I follow Michael explanation, we do not need to verify a) or d)

Currently, master is doing a) and b) but is not doing c) and not doing rank 3/6 verification.

another verification could be
ep square is valid only if our king is not
e)     in double check
    or in check by a knight,
    or in check by a pawn other than the pawn in front of ep square,
    or in check by Q, R or B though a line which does not intercept the square behind the ep square.

because in all those case, last move was not from behind of ep square to front of ep square.

**Comment by siemanko** [comment]
Hey,

Thank you very much for detailed explanations. After doing some more digging I now understand the handling of en-passant squares in FEN notation varies by implementation. E.g. it seems that `python-chess` bit the bullet and just implemented multiple versions. 
https://github.com/niklasf/python-chess/blob/master/chess/__init__.py#L2196-L2201

**Comment by siemanko** [comment]
Thank you very much for detailed explanations. After doing some more digging I now understand the handling of en-passant squares in FEN notation varies by implementation. E.g. it seems that `python-chess` bit the bullet and just implemented multiple versions (with checking if there exists legal en-passant being default): 
https://github.com/niklasf/python-chess/blob/master/chess/__init__.py#L2196-L2201

According to their definitions stockfish's FEN is actually closest to X-FEN ([wiki](https://en.wikipedia.org/wiki/X-FEN#Encoding_en-passant) seems consistent on this) and true FEN would just output `st->ep_square` without any checks.

Either way, for my purposes, I wanted to verify equivalence between the bindings to stockfish and `python-chess`, so I just accomplish that by iterating by legal moves generated by movegen and updating fen if no legal en-passant move is found. It's potentially slow, but FEN is meant for debugging anyways.
