### ISSUE TITLE
[NNUE] Option Use NNUE should be default true

### ISSUE THREAD

**Issue by nguyenpham** [official-stockfish/Stockfish#2861]
The logic is when a user downloads and tries a version of Stockfish NNUE, almost time he wants to run it with NNUE evaluation, not the traditional one. However, Stockfish NNUE is not that ready and the user has to set the option `Use NNUE`. One more step needed. Even that is quick but may make confused, raising some questions and the user has to learn after a while. It is not ready fun for who uses consoles (such as developers) since they have to set that option in high frequency.

If Stockfish NNUE is merged officially, we will consider that default value again (depend on which evaluation will be used more) :D

**Comment by gvreuls** [comment]
Why would most users prefer NNUE evaluation, do you have some numbers on this? I'm having very mixed feelings about this new and untested WIP becoming the default for stockfish already.

**Comment by dorzechowski** [comment]
I'm against setting it to 'true' as a default. This will surprise many (most) users and suddenly Stockfish will stop working for them out of the box. I think users should know what they are doing if they want to use NNUE and opt-in to it.

**Comment by gcp** [comment]
>Why would most users prefer NNUE evaluation, do you have some numbers on this? I'm having very mixed feelings about this new and untested WIP becoming the default for stockfish already.

Why wouldn't you want the program to be ~80-90 Elo stronger?

>This will surprise many (most) users and suddenly Stockfish will stop working for them out of the box

The problem with making sure the net file is bundled is indeed real. The program could silently fall back, but that might confuse users too.

**Comment by gcp** [comment]
By the way, the following argument was made in the original pull request:

>Sure it's qualitatively better than the classic evaluation but we don't know how the code will perform on all platforms and architectures we support yet. Also the new default might surprise a lot of unsuspecting users who just want to upgrade to the new version of stockfish and end up with a configuration that performs miserably (or worse) on their machines

But this exact argument very strongly works out *in favor* of enabling NNUE by default. It is clear that NNUE is considerably better for most machines (or it wouldn't have passed on fishtest/regression testing with +87 Elo). So right now, the "wrong" default of not having NNUE means that "a lot of unsuspecting users that just want to upgrade to a new version of stockfish end up with a configuration that is miserably worse on their machines!"

**Comment by sf-x** [comment]
Autovectorized versions are slow enough to overcome the entire elo gain... not to speak about the architectures without SIMD support.

**Comment by gvreuls** [comment]
@gcp I'm viewing this from the common user's perspective, who I'm pretty sure doesn't know what NNUE is at this point, not to mention that it has different hardware requirements and needs a net file.  If we make NNUE evaluation the default now and release a new stockfish version soon (because +87 Elo sure meets the release requirements) I think a considerable number of these unsuspecting common users are going to get into trouble if we do this (unless we add a net to new releases).

Normally if you have these kind of big new features you make them optional in the first release and protmote them to the default in a followup release. This way users can try the new feature, get a positive experience and tune their configurations to get the most out of it instead of the new feature getting activated without their knowledge or consent with a possible negative experience as a result.

**Comment by vondele** [comment]
@gvreuls adding the default net to the release is something @daylen suggested elsewhere. I think that's definitely a good idea.

**Comment by vondele** [comment]
I'm also not planning to release very soon, just because we reach an Elo target, we need to stabilize things first, and get a feeling for it.

**Comment by vondele** [comment]
so, since this issue was opened 3 weeks ago, we have made quite some progress:

* NNUE is Elo gain on essentially all common hardware (x86 from pentium III upward on, most android devices (arm+neon), all apple silicon, raspberry pi for pi > 1)
* Default net is easy to get (`make net`, download link at abrok, plan to bundle with the official release).
* All of CI, fishtest etc should be able to deal with this.
* NNUE has been tested quite well at large TC/#threads.

There is still the question if or how we could make finding the default net in certain GUIs/tools easy, I will create an issue for this later.

So, have have opinions changed about switching the default? @dorzechowski @gvreuls

**Comment by dorzechowski** [comment]
I'm a bit worried that it will surprise many users for which Stockfish will simply stop working if net is not present/not configured properly. But if not, then it's fine. Probably we need to just do it and see what happens.

**Comment by gvreuls** [comment]
I'm not as worried about the configuration as much anymore as long as a new release plays chess out-of-the-box and doesn't abend (probably the worst thing that could happen is that people's CPUs run really hot and start thermal throttling).

**Comment by bcm314** [comment]
Yes, I'm a little bit late and I see this thread is closed.  :-(

Still I like to ask, why not use this (in ucioption.cpp):
#if defined(NNUE_EMBEDDING_OFF)
  o["Use NNUE"]              << Option(true, on_use_NNUE);
#else
  o["Use NNUE"]              << Option(false, on_use_NNUE);
#endif	

In my eyes, the best way.
