### ISSUE TITLE
(NNUE) Proposal to revert #2585

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#2867]
I really do not understand why this PR was committed.
Definition of a bin file:
A BIN file is a file that stores data in a binary format. It is different than a text-based file, which can be edited in a text editor. BIN files may be created by a variety of different programs but typically cannot be manually edited.

That is exactly what  nn evaluation files are.  There is no confusion here and it is ok to have multiple bin files.  The world is full of bin files.

**Comment by syzygy1** [comment]
I suppose the reason for the change is that the world is already full of bin files. Assigning the .bin extension to all binary files is as useful as assigning the .txt extension to all text files (instead of .c., .h, .cpp, .js, etc.). For polyglot it is probably too late to rename the .bin extension to something more descriptive.

**Comment by vondele** [comment]
yes, that's the reason. It is good to have a little more descriptive file ending, and, contrary to polyglot, at this early stage it seems good to make the change... other tools can likely still change as well. I'll close the issue.
