### ISSUE TITLE
Need CI on windows / mingw

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2958]
See https://github.com/official-stockfish/Stockfish/commit/d7a26899a973536ab9d3ce4771d8276d1a4dc55c#commitcomment-41319808

**Comment by ppigazzini** [comment]
AppVeyor and Travis CI provide msys2.
https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin
https://docs.travis-ci.com/user/reference/windows/

**Comment by niklasf** [comment]
Yet another option would be GitHub actions.

For example, here is a workflow to build binaries for a bunch of different architectures on x86 Linux (gcc), aarch64 Linux, x86 Windows (MINGW), x86 macOS and Apple Silicon: https://github.com/niklasf/Stockfish/blob/fishnet-master/.github/workflows/build.yml

(clang on Linux and MSVC on Windows are also supported, but not included in that particular script, because only one compiler each is needed for its purpose.)

**Comment by vondele** [comment]
now that we have github actions in place, this issue could be fixed.

**Comment by ppigazzini** [comment]
Info about GitHub Actions and mingw-w64:
- [Supported SW on hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software) : Windows hosted runners have already installed `msys2` (first setup, no packages) and `mingw-w64 8.10`, there is also `chocolatey`
- [setup-msys2 action](https://github.com/marketplace/actions/setup-msys2) : info and examples:
  - [msys2 workflow](https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml) : the workflow used by msys2 project to test and upload the msys2 packages
  - [GitHub Actions with msys2](https://ariya.io/2020/07/on-github-actions-with-msys2) : some simple examples
