### ISSUE TITLE
How to compile Stockfish or CFish for iPadOS?

### ISSUE THREAD

**Issue by lex312** [official-stockfish/Stockfish#3131]
I‘m very busy but I have a plan to create a free chess app for everyone for the iPad Pro.
How do I compile Stockfish or better CFish because it‘s much faster than Stockfish?
I have seen the speed increase on my windows machine and on android smartphone and I think that people should use the strongest, fastest and best engine on that incredible iPad Pro.

**Comment by vondele** [comment]
so, what did you try and what failed? Do you have a working toolchain installed (compiler, make, etc..).

**Comment by lex312** [comment]
I tried the things that are mentioned here: https://github.com/syzygy1/Cfish/issues/156

**Comment by nguyenpham** [comment]
SF can’t run independently on iOS (as an independent app). Instead, it must be integrated with a chess GUI by coding. That means you must develop a chess GUI for iOS first, then add SF code to it later. There are several ways/tools to develop a chess GUI as well as integrating with the SF code. Thus there’s no direct answer to your question about compiling SF for iOS since it’s too general.

BTW, adding/compiling SF (to a chess GUI code) is not hard and may take only a few percentages of workload. However, you need a lot of work for developing a new chess GUI for iOS, you need some deep knowledge to modify the SF code to integrate and to make the chess GUI can work smoothly with SF.

Frankly speaking, it is a hard task, time-consuming, thus forget it if you’re so busy and/or lack any knowledge/experience about SF/chess GUI/iOS app.

**Comment by vondele** [comment]
I'll close this based on the comments made.
