### ISSUE TITLE
Use only nnue evaluation

### ISSUE THREAD

**Issue by voyag** [official-stockfish/Stockfish#3173]
Is it possible to add an uci option for using only the nnue evaluation instead of the hybrid one?

**Comment by Sopel97** [comment]
nodchip/master has a 3 state Use NNUE already with options "true", "false", "pure"; so doing this would not be hard

**Comment by rconstant42** [comment]
It seems that **pure NNUE evaluations finds quickly solutions on bad positions**. In some positions, standard SF (with hybrid eval) cannot find the best move to get out of losing positions because the imbalance is so important that it uses only standard evaluation and not NNUE eval any more. And if you "force" CFish with "pure" NNUE UCI option to use only NNUE eval, it finds all the best moves in a second.

May be SF should not switch to standard evaluation unless the imbalance between player and opponent is strickly positive and not absolute positive (eval > threshold and not abs(eval) > threshold). This should make SF **use more often Pure NNUE eval when in negative imbalance** so that it would find quickly a way out of losing positions. A try should be done in SF testing framework.

Here are some exemples :
rn1qrnk1/p4pp1/1p1pp3/6P1/2Pp1PN1/2PQ4/P5P1/2KR3R w - - 0 1 bm Nh6+
4k3/4Pp2/1P1p1P1P/pPpPpK2/pr2pbP1/7r/3RP3/NN5b w - - 0 1 bm Rb2
r1n2N1k/2n2K1p/3pp3/5Pp1/b5R1/8/1PPP4/8 w - - 0 1 bm Ng6
rn2kbnr/pp2ppp1/2p5/3pP1Bp/3P3P/3Q4/PqP2PP1/RN2K1NR w KQkq - 0 1 bm e6

**Comment by Sopel97** [comment]
@rconstant42 https://tests.stockfishchess.org/tests/view/5f86dac4dcdad978fe8c51c6

**Comment by rconstant42** [comment]
Thanks for trying

**Comment by vondele** [comment]
This has come up a number of times, and there I still see no new arguments to do 'pure' nnue, it is weaker than what we do so far. There are various parts of the engine that could be disabled to make it weaker in general, but maybe stronger for specific positions.

**Comment by mstembera** [comment]
Given the same reasoning it makes no sense to have pure classic either.  Yet we do.  How do we reconcile this inconsistency?

**Comment by vondele** [comment]
because there is value in retaining what is probably the best hand-crafted evaluation ever written. We do already effectively use it in our 'hybrid' use? I think it is pretty different. The best comparison is, why don't we have an option to disable TT, NMP, LMR, ...

**Comment by mstembera** [comment]
Disabling TT, NMP, etc. seems not a very close comparison because those simply handicap the engine w/o any real benefit. (This is probably why users are not asking for those but are for pure NNUE.) Having pure eval methods on the other hand can provide unique perspectives on positions.  In any case I am not advocating for removing classical.  I am simply pointing out that both pure NNUE and pure classical are weaker than hybrid.  It therefore seems inconsistent that we support a pure version of one and not the other.

**Comment by Sopel97** [comment]
> because there is value in retaining what is probably the best hand-crafted evaluation ever written.

Right now it's probably at stockfish 11 strength. I've seen many people using it as if it was the best but it's not. I think it's even harmful.

**Comment by vondele** [comment]
> > because there is value in retaining what is probably the best hand-crafted evaluation ever written.
> 
> Right now it's probably at stockfish 11 strength. I've seen many people using it as if it was the best but it's not. I think it's even harmful.

the evaluation has been improved, but overall, because integration with search, it might eventually be weaker.

**Comment by syzygy1** [comment]
Also, we don't really know what is best under TCEC-like conditions. At least at first there were many reports of bad scaling of the hybrid solution. Having a pure NNUE option could lead to more data on this question.
