### ISSUE TITLE
Trying to move the stone that is not exist

### ISSUE THREAD

**Issue by ErcinDedeoglu** [official-stockfish/Stockfish#3442]
He made the following series of moves.
Sotckfish 13 (stockfish_13_win_x64) plays on the black side.
On the white side, there is another engine.
There is nothing on **e1** that it wants to move in the last move.

{ d2d4 g8f6 c2c4 e7e6 b1c3 f8b4 g1f3 c7c5 d4d5 b4c3 b2c3 e8g8 e2e4 f6e4 f1d3 e4f6 d1c2 d7d6 d5e6 c8e6 c1g5 h7h6 h2h4 e6g4 a1d1 f8e8 d1g1 **e1f1**}

I worked a little and visualized the movements:
![Screenshot_1](https://user-images.githubusercontent.com/6512072/115960424-0c5baf00-a51a-11eb-8b20-e976c7e91c9e.png)

The part I marked in red is where it tries to move.

**Comment by Sopel97** [comment]
Please post replication steps.

**Comment by rooklift** [comment]
Your move history has white making the first illegal move, d1g1, which is impossible because the king never moved off e1. Your posted image does not correspond to the history you gave.

Your history up until the illegal move by white is:

```
1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. Nf3 c5 5. d5 Bxc3+ 6. bxc3 O-O 7. e4 Nxe4 8.
Bd3 Nf6 9. Qc2 d6 10. dxe6 Bxe6 11. Bg5 h6 12. h4 Bg4 13. Rd1 Re8+ *
```

Which gives:

![image](https://user-images.githubusercontent.com/16438795/115960742-090cf700-a50b-11eb-88dd-981200d4930f.png)

At which point d1g1 is illegal.

**Comment by rooklift** [comment]
It looks like a bug in the white engine, which probably intended to castle long but sent `a1d1` instead of `e1c1`.

**Comment by rooklift** [comment]
And then when Stockfish was sent the illegal move history, it ignored the illegal move and considered the position from the white side, and found that `f1g1` (escaping check) was the best move, which it played. This is working as intended.

**Comment by vondele** [comment]
I agree, not a bug
