### ISSUE TITLE
Remove old .nnue files when building Stockfish

### ISSUE THREAD

**Issue by FredFerguson01** [official-stockfish/Stockfish#3631]
The makefile should also delete the old .nnue file if a new one is found.
Presently, the user is required to delete the older .nnue files manually from /src directory.
This is a problem if many new nets are merged in a short time frame and leads to storage wastage as the net is now embedded in the binary that is build.

https://github.com/official-stockfish/Stockfish/blob/237ed1ef8fddea77779e7fdcde8e4195d92f123b/src/Makefile#L776-L797

**Comment by Sopel97** [comment]
Please no

**Comment by FredFerguson01** [comment]
> Please no

Could you elaborate ?
In my opinion, the src directory should not contain files that are not used to build the binary.
I follow the steps from here 
https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows
and execute makefish.sh on mingw64
Over time, the src directory had numerous .nnue files, when only 1 is needed.

**Comment by Sopel97** [comment]
For one, I have no idea about what storage issues you're talking about. I'm creating more nets than you will ever need to see and they only take up ~2GB in the src directory. I find it **important** that the nets are not deleted, because otherwise development would become impossible. The day you delete all my .nnue files without my consent is the day I quit.

**Comment by FredFerguson01** [comment]
> For one, I have no idea about what storage issues you're talking about. I'm creating more nets than you will ever need to see and they only take up ~2GB in the src directory. I find it **important** that the nets are not deleted, because otherwise development would become impossible. The day you delete all my .nnue files without my consent is the day I quit.

I am not talking about **your** storage space or storage space of fishtest.
I am talking about the storage space of **my** computer when I run the steps from the earlier comment.

**Comment by Sopel97** [comment]
All networks that have been default at some point weigh under 1GB. How is this an issue for you?

**Comment by FredFerguson01** [comment]
> All networks that have been default at some point combined weigh under 1GB. How is this an issue for you?

I don't know what provoked you to this extent. I was talking about user experience.
At no point did I say to delete your nets from fishtest or anywhere else.

All I am saying is that I follow the steps from https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows
Every once in a while when there are a few commits merged, I run makefish.sh again to generate the latest binary.
The source code is replaced in my local machine with the latest one but the net files are accumulated.
I know that they are around 45MB now, but they add up unnecessarily as only 1 is required.
All I am saying that the old .nnue files be deleted automatically in the build process.
What do you find so offensive about that ? Should everyone maintain all the nets they compile because its your architecture ?

**Comment by Sopel97** [comment]
You're the only person talking about fishtest, bending my words to your liking. This issue was pretentious to start with and now I'm considering it a personal attack.

**Comment by FredFerguson01** [comment]
How was this statement related in any way to my issue ?
"For one, I have no idea about what storage issues you're talking about. I'm creating more nets than you will ever need to see and they only take up ~2GB in the src directory. I find it important that the nets are not deleted, because otherwise development would become impossible. The day you delete all my .nnue files without my consent is the day I quit."

**Comment by Sopel97** [comment]
Because you want to force a change that would force-delete all .nnue files in everyone's src directory

**Comment by FredFerguson01** [comment]
I am only talking about the master branch

**Comment by ianfab** [comment]
To maybe clarify some misunderstanding here. Sopel is worried that some custom or newly trained nets might be lost without any way to get them back if a command automatically deletes the NNUE nets. For users who do not train any nets, that of course is of no concern, because they always can get their nets back from fishtest.

However, I fully agree that this is a very unnecessary risk for developers, and it can also cause unnecessary traffic for re-downloading when checking out different versions. Deleting NNUE nets on the file system should therefore always be an explicit action by the user. If really required there could be something like a `clean-nets` target of the makefile, but on the other hand `make clean-nets` would not be much shorter than something like `rm *.nnue` either.

**Comment by Vizvezdenec** [comment]
It's actually getting annoying to develop stuff when you have 90% of files in your directory being .nnue files - it starts to take some time to search for useful .cpp files which I want to change for a patch :)
I agree that this should be on a user but also I agree that user should have a possibility to clean all nnues w/o doing it manually.

**Comment by ppigazzini** [comment]
@FredFerguson01 build scripts updated:
 - unzip automatically overwriting older files
 - keep only the newer "nn-*.nnue" file before starting the build

see:
https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows 

@Vizvezdenec this script could help you (see [this](https://stackoverflow.com/questions/25785/delete-all-but-the-most-recent-x-files-in-bash)):
```bash
# keep only newer "nn-*.nnue" file
cd Stockfish-master/src
ls -tp nn-*.nnue | grep -v '/$' | tail -n +2 | xargs -d '\n' -r rm --
```

**Comment by FredFerguson01** [comment]
> @FredFerguson01 Windows build scripts updated:
> 
> * unzip automatically the github code overwriting older files (avoid the warning message)
> * keep only the newer "nn-*.nnue" file before starting the build process (skip unnecessary net file download, we will have two net files at most after the build process)
> 
> see:
> https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows
> 
> @Vizvezdenec this script could help you (see [this](https://stackoverflow.com/questions/25785/delete-all-but-the-most-recent-x-files-in-bash)):
> 
> ```shell
> # keep only the newer "nn-*.nnue" file
> cd Stockfish-master/src
> ls -tp nn-*.nnue | grep -v '/$' | tail -n +2 | xargs -d '\n' -r rm --
> ```

Thanks @ppigazzini It works. Although I did get a few warnings while executing the new makefish.sh
```
warning: unzip-6.0-2 is up to date -- skipping
warning: make-4.3-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-10.3.0-5 is up to date -- skipping
 there is nothing to do
```
You might want to keep this from the old makefish.sh
```
unzip -v &> /dev/null || pacman -S --noconfirm unzip
make -v &> /dev/null || pacman -S --noconfirm make
g++ -v &> /dev/null || pacman -S --noconfirm mingw-w64-x86_64-gcc
```

Also, the following code would only keep the .nnue file found in evaluate.h
```
cd Stockfish-master/src
nnuenet=$(grep EvalFileDefaultName evaluate.h | grep define | sed 's/.*\(nn-[a-z0-9]\{12\}.nnue\).*/\1/')
ls *.nnue | grep -v ${nnuenet} | xargs -d '\n' -r rm --
```

**Comment by ppigazzini** [comment]
`pacman -S --needed` installs or updates the packages if required, other package managers outputs too that warning if the package is already up to date. The previous code didn't update an outdated package.

I simplified a bit your suggestion:
```
file_nnue=$(grep 'define.*EvalFileDefaultName' evaluate.h | grep -Ewo 'nn-[a-z0-9]{12}.nnue')
ls *.nnue | grep -v ${file_nnue} | xargs -d '\n' -r rm --
```

**Comment by JackWright347** [comment]
If "storage wastage" is the only problem the OP is concerned about in that context, I can't agree. Storage is cheap. Not worth mentioning.

**Comment by Dboingue** [comment]
I did not read the whole issue. but dumping data in a development 
process is a bad habit. I have seen that sort of waste of information 
elsewhere, and I think that elsewhere took the means to not be so 
wasteful. Another kind of waste.  Trajectories.  sorry if this is not 
applicable.  but i thought the post i am replying to had enough 
information to infer.

Le 28/07/2021 à 19:10, JackWright347 a écrit :

**Comment by FredFerguson01** [comment]
> If "storage wastage" is the only problem the OP is concerned about in that context, I can't agree. Storage is cheap. Not worth mentioning.

Right now, the ```make clean``` command cleans all files that are created using the build process like *.o, *.res etc. It also deletes the .EXE that is created.
The .nnue is an **intermediate file** required for the build and is created during ```make```. Once the binary is created, it is of no use just like the object files. 
I can understand to avoid unnecessary re-downloading of the net during builds, it is not deleted. Hence the **issue** to delete only the older ones and keep just one (master) in the /src directory. 

Imagine if some other software kept copies of all their old files on your PC after an update and left it to the user to manually delete them.
Would you like that ?

**Comment by JackWright347** [comment]
> 
> 
> > If "storage wastage" is the only problem the OP is concerned about in that context, I can't agree. Storage is cheap. Not worth mentioning.
> 
> Right now, the `make clean` command cleans all files that are created using the build process like *.o, *.res etc. It also deletes the .EXE that is created.
> The .nnue is an **intermediate file** required for the build and is created during `make`. Once the binary is created, it is of no use just like the object files.
> I can understand to avoid unnecessary re-downloading of the net during builds, it is not deleted. Hence the **issue** to delete only the older ones and keep just one (master) in the /src directory.
> 
> Imagine if some other software kept copies of all their old files on your PC after an update and left it to the user to manually delete them.
> Would you like that ?

This is how Windows Update behaves for example, it also doesn't automatically delete all replaced versions of *.dll and *.sys and *.exe etc. but archives them and this way you can later revert an update to the previous version as well. This consumes extra space, yes but many like this option apparently, otherwise you would always have to reinstall Windows to revert to a previous patch level.

Likewise, after a 'make clean' like you want, it would no longer be possible for a developer to quickly revert to a previous version of a .nnue after a git switch or revert without downloading that file again. If you do this often, comparing different versions of .nnue and switching back and forth between branches, I could imagine that such an unintelligent 'make clean' behavior would be quite annoying over time for developers who frequently test, bench and compare different versions.

By the way, typing 'rm *.nnue' is even one character less than 'make clean' ;-)

**Comment by vondele** [comment]
I'm not in favor of removing .nnue files automatically, or as part of the clean target. They should be considered part of the source, just not integrated in git, because git is not suitable for this. Having to download the .nnue on every make would be inconvenient (e.g. I've been coding on a laptop in a plane). Furthermore, deleting .nnue files that might be unique and can't be easily regenerated (i.e. trained) would be a serious risk. Finally, a user that wants to remove them types `rm *.nnue` which is easier to remember than any make target we come up with.
