### ISSUE TITLE
 warning: array subscript is above array bounds

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#3688]
When I build SF with
make -j build ARCH=x86-64 debug=yes
I get:
syzygy/tbprobe.cpp: In function ‘Ret Stockfish::{anonymous}::probe_table(const Stockfish::Position&, Stockfish::Tablebases::ProbeState*, Stockfish::Tablebases::WDLScore) [with Stockfish::{anonymous}::TBType Type = (Stockfish::<unnamed>::TBType)0; Ret = Stockfish::Tablebases::WDLScore]’:
syzygy/tbprobe.cpp:746:30: warning: array subscript is above array bounds [-Warray-bounds]
             if (d->pieces[i] == pieces[j])
syzygy/tbprobe.cpp: In function ‘int Stockfish::Tablebases::probe_dtz(Stockfish::Position&, Stockfish::Tablebases::ProbeState*)’:
syzygy/tbprobe.cpp:746:30: warning: array subscript is above array bounds [-Warray-bounds]
             if (d->pieces[i] == pieces[j])

SF still builds and seems to work fine.

**Comment by JackWright347** [comment]
Nothing to worry about, I guess. This is just one of dozens warnings I also get when I compile it. But that's okay, since it's established that Stockfish is like that "by design". Unless you find someone else who's time is not valuable and doesn't mind their time, or you pay them to fix it. That's the root of the issue. Otherwise, you're the only one who's bothered. Don't forget: as long as it doesn't crash, it's fine. Even if it crashes, it's still fine (because it's not possible to make it better, you can read about it in the forums). The founding fathers have already considered all this, so why would you get worked up over such trivialities?

**Comment by vondele** [comment]
when I checked this long ago, this warning was a false positive, depending on the compiler version.
Note that we compile with `-Werror` a flag that turns warnings into errors as part of our CI:

https://github.com/official-stockfish/Stockfish/blob/84b1940fcae95bb0a641dda9e85cb96f8c21cd22/.github/workflows/stockfish.yml#L19

As a consequence, with our default tool chain, we have no warnings.
