### ISSUE TITLE
Clarification of Testing Procedure

### ISSUE THREAD

**Issue by SFisGOD** [official-stockfish/Stockfish#3695]
https://tests.stockfishchess.org/tests/view/613709dd0cd98ab40c0c9e22
https://tests.stockfishchess.org/tests/view/613668860cd98ab40c0c9ddd

These two tests suggest that some people are not confident with the current testing procedure. Perhaps, we can discuss what needs to be changed? @vondele 

See these discussions:
https://github.com/candirufish/Stockfish/compare/c31fc8d163...d4d3864fa3
https://github.com/TopoIogist/Stockfish/compare/c31fc8d163...f7883ce9b0

**Comment by vondele** [comment]
as far as I can see, these tests essentially confirmed that our current testing procedure works fine. 

Somehow, the error bars are a piece of the information (at NCM or for our tests) one should not ignore. Sometimes results might be surprising at first sight, but we should realize that results we obtain are subject to some statistical uncertainty. So far, we have managed pretty well to deal with it. We should not make a habit of retesting patches, but from time to time it is acceptable and helps to increase the confidence in our procedures.

**Comment by SFisGOD** [comment]
@vondele The thing is, the author did not provide any reason why he suspects this net change is the one possibly causing a regression. Out of the three commits, I find it extremely absurd that he only tested this one and not the other two. If the intention really is to find incompatibility issues, then the more appropriate way is to submit 3 tests, removing one at a time. Also, these tests should be -1 priority or lower as this kind of testing is counter-productive.

**Comment by TopoIogist** [comment]
@SFisGOD In the test I wanted to check for the possibility that applying a net and two search
patches simultaneously could lead to a regression. It is natural to check this by either
reverting the net or both search patches. I agree now that it would have been better
to just test reverting all three patches.

I know that your tuning of this net was a lot of work and in my opinion it is a great
achievement. Please do not think that I submitted the test in bad intent.

For the priority issue I usually prefer to use throughput to throttle less important tests.
Otherwise the test would have been stalled possibly for days and running a single
10+0.1 SPRT test with half throughput will not affect fishtest in any reasonable way.

**Comment by NKONSTANTAKIS** [comment]
We might have interpretation problems with NCM results, because in the past it was just the error bars, and book bias difference was around 20-30, but now not only the error bars are rising, but bias difference is around 120-140.

So we have no way to know which part is statistical error, which is due to optimization differences between biased/unbiased books, and which is due to facing SF7.

@vondele Maybe to ask for NCM gamecount increase to 40K? We have reached +/- 6.35
Or to just not pay too much attention to NCM runs, and just look the general trend.
