### ISSUE TITLE
SF bench 'mixed' default is ill-chosen

### ISSUE THREAD

**Issue by dsmsgms** [official-stockfish/Stockfish#3889]
Some contributors have suggested or possibly established with their due authority multiple times that classical eval is 'frozen'. When it comes to possibly ELO gaining patches, I find that very strange, but this is not the most important issue.

But, rather, that Stockfish 'bench' functionality tests the engine with NNUE completely disabled for 50% of the test positions. Considering classical eval has a purely auxiliary role, this is completely meaningless, for example, if we use 'bench' as a simple speed test or in other common use cases. The default value for 'evalType' in benchmark.cpp:122 should be 'NNUE' instead.

**Comment by vdbergh** [comment]
Please calm down.

Concerning the speed test you have point.

But stating that the current bench is "completely meaningless" is a major exaggeration. The *primary function* of the bench is to produce a signature for a specific SF version. And for that it matters little what eval  is used.

**Comment by dsmsgms** [comment]
If that is the case why so many options to bench?

**Comment by vdbergh** [comment]
I think the extra options are there for mainly speed tests. As I said already, concerning speed tests you have a point. But 99% of the bench invocations are to provide a signature. 

I am just objecting to the tone of your opening post.

**Comment by dsmsgms** [comment]
It is also used by the profile-build target in the Makefile. Also 99% of what exactly, do you have real statistics? Why would you object that I am exaggarating and then do so for rhetorical effect?

**Comment by vondele** [comment]
The bench command indeed servers multiple purposes, and that's why there are various options. Depending on the workflow you have, one set of options might be more useful than another. For the purpose of obtaining a signature of the code, covering the code fully, the current choice is pretty good, independent of implementation details (using hybrid or not), the full code is covered. My local speed measurement script passes the NNUE option, that makes sense. Changing defaults will always impact someone's workflow (https://xkcd.com/1172/)

Concerning profile-build, I doubt it matters much what option is being passed, but reliable measurements of that would be welcome.

Finally, yes, classical evaluations should be considered frozen. It makes no sense to try to improve it, since the impact on strength with NNUE will be very small at best, and we thus can't justify spending significant fishtest resources on it. It makes sense to conserve it as is, it probably is the best classical evaluation there is, and probably it will serve us in the future, one way or another.
