### ISSUE TITLE
Overlapping comparison in syzygy

### ISSUE THREAD

**Issue by fileability** [official-stockfish/Stockfish#394]
Clang found [this](https://github.com/official-stockfish/Stockfish/blob/dc130042831cdb52994aa8165b1cf8f49eef8640/src/syzygy/tbprobe.cpp#L627).

    if (v1 >= 0 || v1 < 100)

which doesn't seem entirely intentional.

**Comment by syzygy1** [comment]
Correct, it should be "v1 >= 0 || v1 < -100".

This is part of en passant handling. v1 is the DTZ score after the en passant capture, v is the DTZ score of the position assuming no ep is possible (the tables don't store en passant positions). The code then takes the "best" of v and v1 (unless the position without ep is stalemate!).
We are in the case that v indicates a loss (-100 <= v < 0). That means v1 is "better" if it is a draw or (cursed) win (>= 0) or a "cursed(/blessed) loss" (< -100).
If v1 is also a loss, it is never better than v, because the ep capture is a zeroing move so the ep capture loss is never better than any other loss in terms of DTZ. (As you can see from the code, v1 is one of -101,-1,0,1,101. So the condition could also be replaced by "v1 != -1".)

The probing code of my private engine has the same typo / bug.

**Comment by mstembera** [comment]
@syzygy1 and @lantonov
Could you please confirm Joonas understanding of the patch here?
https://github.com/official-stockfish/Stockfish/pull/415
Thank you!

**Comment by syzygy1** [comment]
Yes, 100 should be changed to -100:
if (v1 >= 0 || v1 < -100)

**Comment by mstembera** [comment]
Thank you!  But does Joonas explanation of the logic here
https://github.com/official-stockfish/Stockfish/pull/415
make sense?

**Comment by syzygy1** [comment]
I already gave an explanation on github.

**Comment by lantonov** [comment]
Below is the RdM's explanation for "cursed win" and "cursed loss" in syzygy which are indeed connected with the 50-move rule.

"Anyway, this is all not a problem for my tablebases. If the engine wants to ignore the 50-move rule for tablebase positions, it can ignore the 50-move rule when using my tablebases. This is because my tablebases do not store a draw by the 50-move rule as a draw, but as a "cursed win" or "cursed loss". The engine can simply treat "cursed wins" as real wins and "cursed losses" as real losses. Or it can honor the 50-move rule and treat both of them as draws. Or it can bluff and treat cursed wins by the engine as wins and cursed losses as draws."

So, RdM's explanation for what this patch does:

"This is part of en passant handling. v1 is the DTZ score after the en passant capture, v is the DTZ score of the position assuming no ep is possible (the tables don't store en passant positions). The code then takes the "best" of v and v1 (unless the position without ep is stalemate!).
We are in the case that v indicates a loss (-100 <= v < 0). That means v1 is "better" if it is a draw or (cursed) win (>= 0) or a "cursed(/blessed) loss" (< -100)."

is indeed correctly understood by Joona who describes it more clearly.

I wanted to test this patch on the framework but it does not test syzygy at present. Another option is to find positions close to endgame that include en passant moves and test with or w/o syzygy.
