### ISSUE TITLE
Wait...

### ISSUE THREAD

**Issue by benbongty** [official-stockfish/Stockfish#3994]
I have downloaded Stockfish 15 and let it play a match with Stockfish 14.1 on Lucas Chess.

Stockfish 15 and 14.1 have 4 cores and 1GB hash

Timers are 15s and 15s

But why Stockfish 15 loses 14.1?
![image](https://user-images.githubusercontent.com/70845920/164505310-9ca9900a-be07-4564-a1b1-5074ffae0194.png)

**Comment by benbongty** [comment]
Oh, that just an ultrabullet match. Rapid stockfish 15 draws with stockfish 14.1 ;-;

**Comment by benbongty** [comment]
but wait, stockfish 14.1 wins all the time ;-;

**Comment by benbongty** [comment]
![image](https://user-images.githubusercontent.com/70845920/164506298-381be995-0810-4cc8-86c4-ebb8dfc909ce.png)

**Comment by movepicker** [comment]
it is possible even stockfish 15 loses stockfish 5 !!!! because  stockfish newer version are very weak  in single core

you must set core number at least 32 if you want to stockfish 15 defeat all other of version 

`setoption name threads value 32`

**Comment by benbongty** [comment]
> it is possible even stockfish 15 loses stockfish 5 !!!! because stockfish newer version are very weak in search at single core
> 
> you must set core number at least 32 if you want to stockfish 15 defeat all other of version
> 
> `setoption name threads value 32`

so....
is full 8 core enough...? My pc only have 8 cores;-; (i9 9900k)

**Comment by benbongty** [comment]
or even use 2 pcs?

**Comment by benbongty** [comment]
![image](https://user-images.githubusercontent.com/70845920/164705105-ce73c0f0-e276-466d-bb37-58d897a4d60a.png)
Oh ok , Stockfish 15 has won 14.1 bullet 18s but I need to allocate 8 threads;-; Thanks

**Comment by benbongty** [comment]
![image](https://user-images.githubusercontent.com/70845920/164705458-e6417467-ab2c-444c-ab74-c658e4b3b30b.png)
heres the result, thanks

**Comment by benbongty** [comment]
![image](https://user-images.githubusercontent.com/70845920/164708454-aa03800a-8bd1-488b-a53d-51c6b95b0af6.png)
There is it, Thanks!! @movepicker !

**Comment by movepicker** [comment]
you dont need 32 core number, but just set core number to 32 

if your pc has 8 core number, you set at least stockfish core number to 16  :

`setoption name threads value 16`

**Comment by dubslow** [comment]
SF15 is known to be weaker at ultrabullet time controls -- less than 500,000 nodes per move. However, if you use 1,000,000 nodes per move, or greater, than SF15 will handily beat prior versions -- with enough sample size. In a small sample size, anything can happen. (In a TCEC bonus recently, two identical versions of Stockfish were playing each other, only one side had a 25% time handicap. For one opening-pair out of 50, the quarter-time Stockfish beat the full-time Stockfish, because no engine is perfect.)

If you get consistently 1,000,000 nodes per move, and play 1000 or 10000 games with varied openings, you will find that SF15 handily beats SF14.1.

**Comment by vondele** [comment]
closing based on the reply above. SF15 is generally significantly stronger than SF14.1
