### ISSUE TITLE
Nodestime losses on time and incorrect time output

### ISSUE THREAD

**Issue by kayn1208** [official-stockfish/Stockfish#4329]
### Describe the issue

The image below shows that Stockfish used 189 seconds for the first move but it displays that it used 12 hr and 45 mins!
![image](https://user-images.githubusercontent.com/84033193/211164246-c0866f53-1aa5-40de-9b5c-ae0fa7dd8d73.png)

Rubi on Discord tested it as well and SF lost on time.

Logs:
https://pastebin.com/qaB7CxAu

### Expected behavior

Not losing on time and also displaying the correct time output.

### Steps to reproduce

Step 1: Create a 300+3 TC game with SF
Step 2: Make SF use nodestime=10000
Step 3: Start the game

### Operating system

All

### Stockfish version

9fe9ff0

**Comment by Matthies** [comment]
Discussion about the problem here: https://discord.com/channels/435943710472011776/1032922913499783169/1061319366504886272

**Comment by vondele** [comment]
if you use nodestime=10000 with a 300+3s TC, you effectively tell SF to use 300*1000*10000 + 3 *1000 * 10000 nodes for the game, and to ignore the TC. That will only work if you SF actually runs at more than 10+Mnps.

**Comment by kayn1208** [comment]
With nodestime=1 it seems to not lose on time anymore but still displays wrong time (It says it used 14 sec but in reality it used 0.013 seconds on the last move)
![image](https://user-images.githubusercontent.com/84033193/211166522-460edd3f-8f1a-40fc-b93d-d67a8a76a5d1.png)

Logs:
https://pastebin.com/imZD92t5

**Comment by vondele** [comment]
The time it reports are now in nodes, as it is using nodes as time : `nodes 14964 nps 1000 time 14964` this is all consistent

**Comment by kayn1208** [comment]
It made that moved instantly and not 14-15 seconds? Or I'm missing something

**Comment by vondele** [comment]
yes, but the unit of time is redefined by our passed option. nodestime=1 -> 1 node is 1 ms. It played 14964 nodes, so 14964 ms and it plays that at a rate of 1000 / s.

**Comment by kayn1208** [comment]
Ahh. I get it now

**Comment by kayn1208** [comment]
I guess I can close this issue now

**Comment by maximmasiutin** [comment]
According to https://github.com/official-stockfish/Stockfish/issues/4329#issuecomment-1374568656 when the `nodestime` option is set, the engine is limited not by the wall time consumed but by the total amount of nodes searched per game, calculated once per game. The initial time control values are used as source values to be converted to the number of total nodes; however, the source time control settings are not used per turn, but if it were just one turn per game, i.e., the setting of 300 seconds plus 3 seconds increment per move are converted to a total of 303 seconds and then multiplied by `1000 * nodestime`; the result is used as the total number of nodes searched per game. 

E.g., suppose you specified `nodestime = 600`, and time control of 300 seconds plus 3 seconds per move (300+3s). In that case, the maximum total number of nodes searched per game by the engine is `303 * 600 * 1000` = `181800000` (one hundred eighty-one million, eight hundred thousand), regardless of how much wall time it will actually take.

**Comment by maximmasiutin** [comment]
However, if you use the `nodestime` option in an engine run from an external time control software, such as `cutechess-cli`, make sure that the engine running on your computer is able to handle that amount of nodes per second (`nodestime*1000`). Suppose that your computer and the engine is able to calculate a maximum 900000 nodes per second. In this case, the maximum reasonable value for `nodestime` is 900, which is 900 nodes per millisecond, or 900000 nodes per second. Otherwise, `cutechess-cli` will report that your engine lost on time. In your example, you set `nodestime=10000`. In this case, your computer should be able to handle 10 million nodes per second. This performance is unlikely with a single thread. Best processors today are able to handle less than 3 million nodes per second in single-threaded mode.
