### ISSUE TITLE
Docs request: default value and type of Skill Level, UCI_Elo, UCI_LimitStrength

### ISSUE THREAD

**Issue by jamesbraza** [official-stockfish/Stockfish#4418]
### Describe the issue

From https://github.com/official-stockfish/Stockfish/issues/3358#issuecomment-781346012, I have gathered:
- `Skill Level: int`
- `UCI_Elo: int`
- `UCI_LimitStrength: bool = False`

It would be good to place this into the `README.md`.

### Expected behavior

It would be good for the `README.md` to detail the type and default values of each engine parameter.

### Steps to reproduce

n/a

### Anything else?

n/a

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by dav1312** [comment]
1) Not an issue with the engine, this is just how UCI works.
2) This repo already has a [wiki](https://github.com/official-stockfish/Stockfish/wiki/Commands) explaining all of this and that it also has examples.

**Comment by Disservin** [comment]
Also when typing `uci` in the command line it gives the requested information.
```
option name UCI_Chess960 type check default false
option name UCI_AnalyseMode type check default false
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 1320 min 1320 max 3190
option name UCI_ShowWDL type check default false
```

**Comment by jamesbraza** [comment]
Thanks @Disservin, that helps me out!

And yes @dav1312, I see the Wiki now.  In my defense, the Wiki is only mentioned once at the bottom of the `README`, where I hadn't read.  Imo, it would be good to promote the Wiki near the top of the `README` too.  For example, [`isort`](https://github.com/pycqa/isort) makes finding the non-`README` docs obvious.

Feel free to close this issue, if you think this isn't worth adding to the `README`.

Fwiw, I think there should be one source of truth.

**Comment by dubslow** [comment]
> This repo already has a [wiki](https://github.com/official-stockfish/Stockfish/wiki/Commands) explaining all of this and that it also has examples.

This is terrible advice for most users, who get a binary from who-knows-where and have no idea what a git or a github even is. Proper documentation *with the release* is always a large benefit, no matter how good the docs in other places are.

> Also when typing `uci` in the command line it gives the requested information.

Also useless for most beginners, unfortunately. But sadly, previous attempts at improving the beginner user experience have all been rejected.

**Comment by dav1312** [comment]
> This is terrible advice for most users, who get a binary from who-knows-where and have no idea what a git or a github even is. Proper documentation _with the release_ is always a large benefit, no matter how good the docs in other places are.

This is displayed in the first line of the readme, aiming directly at those users that don't know what they are going, because if a user is not knowledgeable enough they are 1) not going to download Stockfish, they are going to use a GUI or 2) be confused the moment they try to execute the program (see the Discord help channel for examples of this).

> "Stockfish is not a complete chess program and requires a UCI-compatible graphical user interface (GUI) (e.g. XBoard with PolyGlot, Scid, Cute Chess, eboard, Arena, Sigma Chess, Shredder, Chess Partner or Fritz) in order to be used comfortably. Read the documentation for your GUI of choice for information about how to use Stockfish with it."

If a user downloads Stockfish and is not confused about what happens when they execute it that means they already know that Stockfish is a command line program and know what UCI is so it is safe to asume they know what git and github are.

Do I mind about having a link to the wiki in the readme? No.
Should the readme be used to host all of the documentation about how to use Stockfish? Also no.
In fact I would prefer it the entire readme was reduced **as much as possible**, removing all of the duplicated and outdated stuff, the wiki is much easier to navigate and keep up to date.

If you go to popular repositories, you will see that their readmes are usually _not that long_ and don't host much information, they usually host the most basic things to get started and then link to other resources where more information can be found. e.g https://github.com/facebook/react, https://github.com/vuejs/vue, https://github.com/tensorflow/tensorflow, https://github.com/twbs/bootstrap, https://github.com/flutter/flutter, https://github.com/torvalds/linux, https://github.com/microsoft/vscode.

**Comment by Disservin** [comment]
Good idea, @dav1312 . I agree that a large part of the readme has become redudant. @vondele do you agree with what dav wrote? If so one may put the effort into cleaning it up.

**Comment by vondele** [comment]
yes, in principle I agree the readme could be much shorter, and that we avoid duplication. The wiki is a better place to put the information. The only small caveat is that it would be nice to somehow 'snapshot' the wiki as part of the binaries we build in CI, and eventually distribute upon release.

**Comment by dubslow** [comment]
I agree that simplifying README, combined with much more prominent links to the wiki/docs, is a good solution. My main concern, tho I poorly conveyed it, was that the existing links were far too easy to overlook or ignore. 4421 goes a long way to improving this.

**Comment by jamesbraza** [comment]
> Also when typing `uci` in the command line it gives the requested information.
> 
> ```
> option name UCI_Chess960 type check default false
> option name UCI_AnalyseMode type check default false
> option name UCI_LimitStrength type check default false
> option name UCI_Elo type spin default 1320 min 1320 max 3190
> option name UCI_ShowWDL type check default false
> ```

Just a comment on the original issue (for posterity), one can also get this info with the [`chess` Python library](https://pypi.org/project/chess/):

```python
import chess.engine  # Version 1.9.4

ENGINE_PATH = "/opt/homebrew/bin/stockfish"  # Version 15.1 via macOS homebrew

engine = chess.engine.SimpleEngine.popen_uci(ENGINE_PATH)
print(engine.options["UCI_Elo"])
# Option(name='UCI_Elo', type='spin', default=1350, min=1350, max=2850, var=[])
print(engine.options["UCI_LimitStrength"])
# Option(name='UCI_LimitStrength', type='check', default=False, min=None, max=None, var=[])
print(engine.options)
# UciOptionMap({...})
engine.close()
```

One comment is `chess` prints have `min`, `max`, and `var` fields that may be unused, so using Stockfish directly with its `uci` command is preferable.

**Comment by vondele** [comment]
I believe this is now fixed, with the wiki documentation more clearly referenced from the readme file, and included in the releases.
