### ISSUE TITLE
Glitchy eval 

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#4699]
### Describe the issue

Starting on move 118 of https://www.chess.com/computer-chess-championship#event=stockfish-16-vs-stockfish-8&game=250 SF suddenly drops the eval to -96.05 and continues like this for a few moves before returning back to 0.   SF8 has no such issue as the opponent.

### Expected behavior

Eval does not glitch.

### Steps to reproduce

See https://www.chess.com/computer-chess-championship#event=stockfish-16-vs-stockfish-8&game=250 starting on move 118

### Operating system

All

### Stockfish version

dev-20230715-ee53f8ed

**Comment by peregrineshahin** [comment]
This is a TB/TT GHI that basically got unlucky
https://github.com/official-stockfish/Stockfish/blob/42d28424bc64246e141e9f06a2a518592272f8fd/src/search.cpp#L1667
(32000-246*2-1)/328 = 96.0579268293

The TB value for this position is saved in TT but for this current position the sequence exceeds the 50 move rule and it seems that a part of the solution is to lower the Eval, I think it's a risky trick but probably outweighs setting Eval to 0 or avoiding the cutoff.

Some view that the probability of it being a mate in 120 plies, that resets the 50mrc every 20 plies is much more likely than a mate in 120 that doesn't reset the 50mrc.

One issue would be that storing unnecessary entries trying to avoid this would most likely lose Elo.
Opinions?

**Comment by peregrineshahin** [comment]
Worth noting that the partial fix we have avoids this risky cutoff from happening only if the 50mrc must reset in the next 10plies  or else it's a draw.
```c++
        // Partial workaround for the graph history interaction problem
        // For high rule50 counts don't produce transposition table cutoffs.
        if (pos.rule50_count() < 90)
            return ttValue;
```

**Comment by peregrineshahin** [comment]
See this game for a countercase: https://www.chess.com/computer-chess-championship#event=ccc20-bullet-finals&game=403
96.05 turned out to work here because the TT entry is usable then the eval changes to 199.29 which tells that the first table base eval is 199.29 so that's probably at least 71 plies for the capture.

**Comment by peregrineshahin** [comment]
I just realized that the line I mentioned has nothing to do with `96.05` value since it's VALUE_MATE_IN_MAX_PLY - 1; (96.814) and not VALUE_TB_LOSS_IN_MAX_PLY - 1 (96.05) 
https://github.com/official-stockfish/Stockfish/blob/42d28424bc64246e141e9f06a2a518592272f8fd/src/search.cpp#L1667
```
return VALUE_MATE_IN_MAX_PLY - 1; // do not return a potentially false mate score
```
and the culprit line is the fix I introduced for the null move issue returning values higher than TB by clamping it to lower than TB range this explains why it happens on pretty low depth as vondele reported.
https://github.com/official-stockfish/Stockfish/blob/42d28424bc64246e141e9f06a2a518592272f8fd/src/search.cpp#L803C2-L807C34
I'm thinking about a better solution now.

**Comment by peregrineshahin** [comment]
OK. I found something else also regarding the 96.05 thing
In qSearch we don't Probe TB's this means that the maximum Best value for new nodes (that are not in TT) is the Static Evaluation and  Since a qSearch PV search can update PV and thus root score. Current guard against pruning in such case is only 
        // Step 6. Pruning.
        if (bestValue > VALUE_TB_LOSS_IN_MAX_PLY)

which means that following moves of the moves loop can be pruned (has no guard) if we only had at least one move that gives us maximum static evaluation (96.05)
The correct way of dealing with this for my mind is to probe TB also in qSearch.

**Comment by peregrineshahin** [comment]
Well this assuming that the net outputs maximum static eval wrongly which we can't do anything about
so 96.05 is indeed safe here 
what is not safe is
what we do in null move search
downgrading a mate/a TB score to that maximum static evaluation ignoring zugzwangs
