### ISSUE TITLE
Randomicity problem

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#4794]
### Describe the issue

I have noticed that when running a game, even with LTC starting from a specific position, Stockfish and its derivatives do not always play the same move. There is randomness, therefore, in the algorithm. Analyzing the code, the only point where it appears in the search is the following:
    `// Choose best move. For each move score we add two terms, both dependent on
    // weakness. One is deterministic and bigger for weaker levels, and one is
    // random. Then we choose the move with the resulting highest score.
    for (size_t i = 0; i < multiPV; ++i)
    {
        // This is our magic formula
        int push = int((  weakness * int(topScore - rootMoves[i].score)
                        + delta * (rng.rand<unsigned>() % int(weakness))) / 128);

        if (rootMoves[i].score + push >= maxScore)
        {
            maxScore = rootMoves[i].score + push;
            best = rootMoves[i].pv[0];
        }
    }`

Why was this randomness introduced in the selection of the "best move"? In fact, it is more pronounced in sharp positions, and if you want to test an engine, you have to choose such positions since the nnue has significantly raised the level of play...

### Expected behavior

Unless strictly necessary, I would avoid this randomness

### Steps to reproduce

Choose a sharp position and play some games of the engine against itself.

### Operating system

All

### Stockfish version

Stockfish 16

**Comment by Sopel97** [comment]
> There is randomness, therefore, in the algorithm.

No. It's an emergent property of 

1. running on an OS that doesn't guarantee deterministic execution times, while being constrained by thinking time.
2. lazy SMP

The code you brought up is only used if UCI skill level is set.

**Comment by amchess** [comment]
Ok. So, it's unavoidable.
Thanks

**Comment by Dboingue** [comment]
What about the evaluation variables type resolution, and the ability to distinguish within such range many branches at depth.  I know it might not affect the play, if such uncertain at depth  were to happen in same leftmost candidate move for the current position (root  for each move  tree searches).  Is this related to the idea that the PVs are not reliable beyond a certain depth when using SF as analytical tool (not same context, I would like to mention)?  What ever reliable or unstable might mean exactly. (I have read both i think).  

It is possible that certain "regions" of chess would be more prone to have flat subtree also at depth.   It might also be possible, that if the engines of similar make up or ancestry (pardon the analogy suggested), had a tendency to stall in such regions  from depth leaf eval.  in such possible flatland at whole searched subtree level, would come up with a good enough but not best or better  (i.e. better if it had better leaf function separation power at depth or anywhere it might have looked actually), faster** than such subtree. 

**
I admit I do not know enough about the internals, and it seems that there is no pressure for such internal data about searched tree details to be available (i think fruit engine might have been the last of its kind in that regard).
I understand that any fishtest variant that would try anything that would help others, non coders, but chess aware and possibly data analysis able to extract chess interesting things, is likely to be a fast regression.  So we have to rely of the generosity of developpers and trust their diligence in going beyond mere ELO endpoints from engine pools contexts (not very well defined in terms of engine to chess diversity of coverage, with competition within same fixed contrainst never studies in relation to chess world size (allow me that undefined), there is no safeguard against subtree search behaviors convergence in their designs. 
More eloboration on that. I like to generate hypotheses, does not mean they are wrong (:).  I might very well be that this idea that faster decision and regression at internal transparency about actual coverage of chess (maximum would be legal, but the searches could still be entire tree coverage initial program abiding with some strict AB pruning. long gone such abiding).  We might have a lot of chickens gaining ELOs in their sandbox..   

ok far from the uncertainty topic.   but not unrelated. if it is related to resolution of leaf evaluation, and development choice of internal nature. that nobody at the tournament format thought of putting as possible categories of engine competition.

We might finally share and test the hunches and convictions about where the randomness might come from on some statistical independent basis. Otherwise however good at analysing their own code for their chess statistical behavior, the pressure toward not keeping the means to do that inside the code would allow one to think, it might be a conforting hunch being propagated in same kind of engine designs.   Why risk a regression.  And am I wrong about this? in general, more output code modifications that might introduce unwanted departure from efficient code execution speed, not worth the dev effort of debugging if an regression hint cuts that possibly (across generations of SF from leanring about previous) could look at more global optimal behavior.. 

many ideas above. I think they can all be related..  but not necessary.  I have had those ideas for a while now.. not knowing where it could make sense to share them.. here is another attempt..  so..  mostly questions than answers.. but since there is little analysis of the engine code at execution available directly or by engine tournament newfound imagination (one day, a spark of curiosity?).  I think I can ask them when I can.

chess expertise may happen in a restricted context, and if some competition pressure is already favoring those engines (even among SFs mutants) that steer toward faster tree searches because of the chess properties themselve. would not be something that we could not currently be aware of. never asked. no tools for data analysis. license for imagination and asking such questions.

**Comment by Dboingue** [comment]
the desert of closed issues. keep away those doubts.  :)
