### ISSUE TITLE
root_moves option and three fold repetition

### ISSUE THREAD

**Issue by fazega** [official-stockfish/Stockfish#5007]
### Describe the issue

```
board = chess.Board(fen='6k1/5p2/p6P/1N6/1PP1b3/8/P2q4/5K2 b - - 13 59')
engine.analyse(board, limit=chess.engine.Limit(time=0.1), root_moves=[chess.Move.from_uci('e4d3')])
```

returns:
```
{'depth': 14,
 'hashfull': 12,
 'multipv': 1,
 'nodes': 24554,
 'nps': 243108,
 'pv': [Move.from_uci('e4d3'),
  Move.from_uci('f1g1'),
  Move.from_uci('d2e1'),
  Move.from_uci('g1g2'),
  Move.from_uci('a6b5'),
  Move.from_uci('c4c5'),
  Move.from_uci('d3e4'),
  Move.from_uci('g2h3'),
  Move.from_uci('e1f2'),
  Move.from_uci('h3g4'),
  Move.from_uci('f2f3'),
  Move.from_uci('g4h4'),
  Move.from_uci('f3f4'),
  Move.from_uci('h4h3'),
  Move.from_uci('e4f3')],
 'score': PovScore(Cp(+1004), BLACK),
 'seldepth': 23,
 'tbhits': 0,
 'time': 0.101}
 ```

e4d3 leads to a draw with three fold repetition in this position. Why does it return a score of +1000 if I'm basically drawing the game? Shouldn't I get a score of 0 for this move?

### Expected behavior

See above.

### Steps to reproduce

I'm using the [python-chess](https://python-chess.readthedocs.io/en/latest/) module, and load stockfish win:
```
engine = chess.engine.SimpleEngine.popen_uci(PATH_TO_BIN)
```

### Operating system

All

### Stockfish version

Latest

**Comment by peregrineshahin** [comment]
There is no 3fold repetition here since you are only providing the fen to the engine, Stockfish has no idea about what happened in the game earlier, thus you need to send the whole pgn with every move not fens.

as you can see here the position is a mate in 5 for this move 6k1/5p2/p6P/1N6/1PP5/3b4/P2q4/5K2 w - - 14 60
and not a draw if it had no context.

**Comment by fazega** [comment]
Oh. I thought the FENs contained everything about a board. Do you what other information is missing from the FEN on top of repetitions (and that is relevant for the final score)?

**Comment by peregrineshahin** [comment]
I can't think of anything other than repetitions, since a threefold can happen for any position that was reached before regardless if it was the previous move or the 15th move prior so it makes sense that a one liner like a FEN does not contain all moves or else it would be a PGN of some sort. I guess it's only this.

**Comment by fazega** [comment]
I see, thanks a lot!
