### ISSUE TITLE
 Fix output for GUI #5460 needs change

### ISSUE THREAD

**Issue by Jouni-2024** [official-stockfish/Stockfish#5525]
### Describe the issue

Now it takes up to 30 seconds before current move is displayed with modern CPU!

### Expected behavior

Current move is displayed in 5 seconds.

### Steps to reproduce

Any position like opening.

### Operating system

All

### Stockfish version

Latest dev version

**Comment by xu-shawn** [comment]
This change is intentional, justification:
> To avoid output that depends on timing, output currmove and similar only from depth > 30 onward.  Current choice of 3s makes the output of the same search depending on the system load, and doesn't always start at move 1. Depth 30 is nowadays reached in a few seconds on most systems.

Related Commits:
https://github.com/official-stockfish/Stockfish/commit/5d3517c601c64d026824251784dd44f0cbf14873
https://github.com/official-stockfish/Stockfish/commit/25361e514bffb81284d4311601a9f7a4a7ced79b

**Comment by Jouni-2024** [comment]
I think this is wrong decision. Even if you have AMD EPYC™ 9754 You must wait 30 seconds for currmove. In rapid game yoy never see it.

**Comment by Disservin** [comment]
The limit is 10M nodes. That is if that were true your systems only cracks 333k nps ? And if you use all threads with that cpu it should reach almost immediately 10M nodes ?

**Comment by dubslow** [comment]
`currmove` spam is annoying and im glad its gone (we should delete even more of it)

**Comment by Matthies** [comment]
Jouni may have a point. It seems to me that "nodes > 10000000" test doesn't use the total number of all nodes but only the nodes of main thread. So it takes even longer for currmove to be displayed when using all threads of CPU.

**Comment by Disservin** [comment]
> Jouni may have a point. It seems to me that "nodes > 10000000" test doesn't use the total number of all nodes but only the nodes of main thread. So it takes even longer for currmove to be displayed when using all threads of CPU. But I agree that currmove is quite useless information.

ah right i just had the same thought.. i guess then we can adjust the 10m nodes limit a bit by depending how many threads we use? not sure what a good ratio for this is

While currmove is indeed quite useless I think it provides a sort of nice feedback for the user, signaling that the engine is still searching and doing something

**Comment by Matthies** [comment]
Tbh I don't understand why you replaced the original test "elapsed_time() > 3000" which is imo a perfect way to give a consistent GUI behaviour for the users.

**Comment by robertnurnberg** [comment]
Because it introduced nondeterministic behaviour in single thread mode.

**Comment by mhouppin** [comment]
> Because it introduced nondeterministic behaviour in single thread mode.

It doesn't make the behaviour non-deterministic, it makes the **output** non-deterministic.
Except that this patch still doesn't fix non-deterministic outputs because the time and nps fields from the info line can (and very often will) be different for two identical single-threaded searches on the same CPU.
(Note that I'm not arguing against the patch being added here, but it is IMO fallacious to sell it as something that fixes non-deterministic behaviour.)

**Comment by vondele** [comment]
It reduces non-deterministic behavior, i.e. easier to paste the output of two runs next to each other and corresponding lines will match up.

**Comment by Matthies** [comment]
People who compare raw uci outputs (developers) are able to pipe it through some grep -v currmove.

**Comment by vondele** [comment]
Anyway, the request seems to be see this output more frequently. Clearly, as soon as one analyzes a position a bit more deeply, having to wait for 30s additional output is very common. So, there is small window of TCs where this actually makes a difference.

**Comment by joergoster** [comment]
Maybe this can be reopened.
There are also people complaining about this in the german CSS Forum. See

**Comment by chess-tester** [comment]
I hope SF 17 will be changed as to our wishes.
Kurt

**Comment by Sopel97** [comment]
Can someone help me understand what the significance of this is?

**Comment by chess-tester** [comment]
Computer chess fans are interested in following the ongoing thought process of a chess program during their analyses: which moves are examined, discarded or not considered at all.

**Comment by Sopel97** [comment]
> Computer chess fans are interested in following the ongoing thought process of a chess program during their analyses: which moves are examined, discarded or not considered at all.

But `currmove` goes over all legal moves from root, so I fail to see the logic in your statement?

**Comment by Disservin** [comment]
To explain this a bit,

> which moves are examined, discarded or not considered at all.

"which moves are examined" All legal moves are examined a chess player should know which ones are legal.
"discarded" No moves are discarded.
"not considered" All moves are considered.

The only thing this currmove tells you is in which order they are looked at, which doesn't tell you much since this is based on move scoring heuristics which are a blackbox (One might conclude from the timing of the output how much time is spent for searching a particular root move but this is in itself doesn't tell you much again)

**Comment by joergoster** [comment]
@Sopel97 @Disservin Which GUIs are you guys using to analyse?
In the Fritz GUI (Chessbase) there is a separate little box for showing the currently analysed root move along with the number. This info is now missing, meaning this little info box remains empty for the first 30 seconds which is quite annoying.

**Comment by Sopel97** [comment]
It used to be missing for 3 seconds. What's the amount of seconds that's the threshold for annoying? And is it annoying or is some value lost?

**Comment by joergoster** [comment]
> If it's just annoying then I suggest contacting the GUI developer to remove the box.

Lol, I'm sure they will do only because of Stockfish 17 ...

If anything, I would decrease the time to 1 sec or even 500 ms with nowadays speed of computers and programs.

**Comment by peregrineshahin** [comment]
Since the goal of the new change was to preserve deterministic output for testing then there is an easy solution for all parties.. for the dev who cares about debugging, make the limit as much as you wish... that is only providing most of your work is already done with 1 thread which is.. now for the user and GUI fanatic one can remove this delay completly if more than 1 thread is used.. in such way you also don't need to count nodes for all threads and solve it all.

**Comment by peregrineshahin** [comment]
Worth noting that no delay can keep determinism if threads are more than 1

**Comment by Matthies** [comment]
Wrong decision to (almost) remove an UCI/GUI standard feature if you never use a GUI yourself but 98% of Stockfish users do. Just another 2ct.

**Comment by peregrineshahin** [comment]
> Wrong decision to (almost) remove an UCI/GUI standard feature if you never use a GUI yourself but 98% of Stockfish users do. Just another 2ct.

If you don't want to remove it completly, You could `or` between the nodes_searched and the time delay for 1 thread vs many thread.. the output being deterministicis makes it a convenient way to write unit tests, since we lately have fallen into breaking it functionally on 1 thread, which is as far as I can tell a nono.

**Comment by peregrineshahin** [comment]
Unless one is a scripting god.. which is making tests complex.. that's the rationale about the new change in case you missed it. Some discrepancy causing false positives discussed..
