### ISSUE TITLE
xx moves in xx time broken

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#603]
Played a 100 game match between SF and K.  Although SF won the match overall (53.5 to 46.5 -   great result), it lost 4 dead draw games on time.  Tc was 3min/40moves. repeating.  Pondering off, 24 threads. Shortest game was 112 moves, longest game was 234 moves.  K did not lose any games on time.

**Comment by MichaelB7** [comment]
Correction:  SF lost 8 dead draw games on time ( 4 points)

**Comment by MichaelB7** [comment]
Games attached
[SFvK316.txt](https://github.com/official-stockfish/Stockfish/files/179100/SFvK316.txt)

**Comment by pb00068** [comment]
Excerpt *: 
For those who are experiencing time losses in engine-vs-engine games with Stockfish 7, try increasing Move Overhead to 1000. You can do this in the UCI settings for Stockfish in your GUI.

Move Overhead is an internal variable in Stockfish that compensates for any outside environmental noise in its time management algorithm. It is set in milliseconds, so a value of 1000 would force stockfish to keep a 1 second buffer before making a move. 1000 is just to be on the safe side. You can experiment with lower values in your setup if you wish.

This issue is most common to Windows and Arena GUI when run in multithreaded mode. Unfortunately there is no known clean solution at this point. The root causes of the issue are complex and still not well-understood. Hopefully, it will be fixed in Stockfish 8.

* excerpt taken from  [https://www.reddit.com/r/chess/comments/3z7ubx/stockfish_7_is_out_60_elo_stronger_than_stockfish]

**Comment by mcostalba** [comment]
@MichaelB7 Which GUI did you use?

**Comment by MichaelB7** [comment]
xboard with -noGUI option

  Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	6-Core Intel Xeon
  Processor Speed:	3.46 GHz
  Number of Processors:	2
  Total Number of Cores:	12
  L2 Cache (per Core):	256 KB
  L3 Cache (per Processor):	12 MB
  Memory:	48 GB

**Comment by zamar** [comment]
@MichaelB7: So you had 12-cores, and you ran a test with 24 threads. Does your processor support hyperthreading?

Is this problem only specific to x moves/ y minutes time control? Or do you have similar problems with other time controls as well?

**Comment by MichaelB7** [comment]
Yes, all Mac Pros since the 2009/Nehalem series support HT.  machine in
question is Mid 2010 Mac Pro with the Westmere processor.  Have only seen
this issue with xx moves / y minutes.   By far most of the games I run are
with base/increment with base = 60 * increment - have never seen this issue
with that type pf  time control even though most of the games are micro
bullet.  Here I run just 100 games with 3 min base and 3 sec increment and
8 % of the games are forfeited  on time.  For what's it worth , every
forfeited game on time  had a draw score.

**Comment by zamar** [comment]
Thanks for the quick response @MichaelB7!

I suspect it's caused by some combination of the following:
- Getting very low on time with that time control
- High search depths reached in dead draw positions
- Multithread search being slow to return (especially from high depth) search.

This is something we want to fix for SF8!

**Comment by lp--** [comment]
Maybe it makes sense to have adjustable moveOverhead depending on  time control.
On first run of  Timemanager::init  after receiving ucinewgame   to set something like
MoveOverhead = max( MoveOverhead, min( 1000,  ExpectedLengthOfGame / 2000 ))

Here for 60sec game MoveOverhead will be default 0.03sec, and increase proportionally for longer games. 

If number of threads somehow cause overstepping it possible  use number of threads for adjustment of MoveOverhead  also.

**Comment by lp--** [comment]
@MichaelB7 : I did not understand waht was tc. In the beginning you said  tc was 3min/40 and later you said 3min+3sec/move. In both these cases there are time losses, but only if you run with 24 threads? For lower number of threads there are no time loses?

**Comment by MichaelB7** [comment]
Sorry, I misspoke , games were 3min/40 .  I have not had any time forfeits in  single thread - but they are usually  base + inc variety 10 sec base / .17 sec inc .    I have not tested tc 3 min +3 sec recently.  Not sure where that came from.

**Comment by XsupremeX** [comment]
Hi Michael. You said you use xboard with -noGUI option. How set time in codes to engine plays specific time? Thx!

**Comment by MichaelB7** [comment]
Use the GUI time to set all of your tournament parameters , including time controll, start your tournament - then quit the tournament before it finishes the first game , add "-noGUI" to the "trn" file and restart the tournament.

**Comment by Mindbreaker1** [comment]
I am getting these losses as well. But only with MinGW builds. I am getting them with ordinary 64-bit builds, not sure if it extends to "modern" builds.

**Comment by Mindbreaker1** [comment]
I made a discovery today.  I happen to be watching the CPU utilization in the Task Manager when it dropped a bit.  Then 20 seconds later there was a time loss reported. It went up immediately afterwards.  I watched for another 20 minutes when the same thing repeated itself, a drop followed by a time loss, then an immediate resumption of previous levels.  This can only mean one thing, Stockfish is freezing.  Maybe it is Little Blitzer's fault, asking one more move of an engine than is required for 50 move rule or some other end of game reality.  Maybe insufficient material?  I don't know.  Little Blitzer does not report in the pgn what the cause of the result is.  We should insure that the engine will continue to play regardless until the GUI stops the engine or there is a checkmate or stalemate.  Judging from the pgn files I have seen though Stockfish is stalling early in some of the games.  That does not seem easy to track down.  asmFish does not seems to have the same thing happen to it.  Don't know if that is useful.  And it is happening with the "modern" MinGW builds as well.

**Comment by vondele** [comment]
what about testing #1192

**Comment by MichaelB7** [comment]
I'm closing this - just ran a 300 game match with tc 40 moves in 10 seconds - no flags fell with either master or  https://github.com/official-stockfish/Stockfish/pull/1192 .
