### ISSUE TITLE
Build fail on ARCH=armv7

### ISSUE THREAD

**Issue by aprijal-psrb** [official-stockfish/Stockfish#638]
$ make build ARCH=armv7
....

error: unrecognized command line option '-m32'

**Comment by mcostalba** [comment]
What is your platform? For which hardware you are building for?

**Comment by aprijal-psrb** [comment]
I'm build it from android ndk compiler, of course for android

**Comment by aprijal-psrb** [comment]
I'm trying to remove "-m$(bits)" from Makefile line 148, building successful

**Comment by enricoT** [comment]
compiled on raspberry with 3 changes (pi 3 B) sorry for bad form:
i added -ldconfig += -lpthread to compile on raspberry in section if arch=armv7
armv7h doesnt work on raspberry pi 3 i had to put armv7 in -march=
i had to remove bits=32 from main line because it's not an option recognized -m32 and make crashes and stockfish bench works!
