### ISSUE TITLE
Make draw move in winning endgame with syzygy

### ISSUE THREAD

**Issue by aprijal-psrb** [official-stockfish/Stockfish#658]
This issue occur after stockfish_16041611_x64_modern.exe build (abrok build), which in PR #631 
Can produced by:

setoption name Threads value 4
setoption name SyzygyPath value D:\DataKu\Games\Chess\TB\Syzygy
position startpos moves g1f3 d7d5 e2e3 c7c5 d2d4 g8f6 c2c4 e7e6 b1c3 b8c6 a2a3 a7a6 d4c5 f8c5 b2b4 c5d6 c1b2 e8g8 c4d5 e6d5 f1e2 f8e8 e1g1 c8e6 a1c1 a8c8 b4b5 c6e5 f3e5 d6e5 d1d2 d8e7 b5a6 b7a6 e2a6 e5h2 g1h2 f6g4 h2g1 e7h4 f1e1 c8d8 c3b5 d5d4 b5d4 h4h2 g1f1 h2h1 f1e2 h1g2 e2d1 g4f2 d1c2 g2e4 a6d3 e6b3 c2b3 f2d3 b3a2 d8b8 b2c3 h7h5 c1d1 d3e1 d1e1 h5h4 e1g1 g7g6 g1e1 b8b6 c3b4 g6g5 d2f2 e8a8 a2b2 e4d3 d4b3 a8c8 e1f1 f7f6 f1b1 h4h3 e3e4 b6c6 b3c5 d3d6 b1c1 d6e5 b2a2 g8g7 f2g1 c6c5 c1c5 h3h2 g1g2 c8c5 b4c5 e5c5 g2h2 c5c4 a2b2 c4e4 h2g3 g5g4 b2c1 e4d4 c1c2 g7h6 c2b3 h6g5 a3a4 d4d5 b3b4 d5e4 b4b5 e4e5 g3e5 f6e5 a4a5 g4g3 a5a6 g3g2 a6a7 g2g1q a7a8q g1b1 b5c5
go movetime 500
go movetime 500 ....(few times / can be many times)

Sometimes sf will play e5e4 or b1c2 (draw). That is the move without syzygy. Is that any wrong code in PR #631 ?

**Comment by zamar** [comment]
@aprijal-psrb: Have you checked that this problem doesn't occur before #631?

**Comment by aprijal-psrb** [comment]
Yes

**Comment by aprijal-psrb** [comment]
Sorry, i don't check before #631 (PR), but i check sf_160416 (abrok build) which it's before #631

**Comment by aprijal-psrb** [comment]
I've check the PR, it's positive in #631

**Comment by Rocky640** [comment]
According to my tests, tt seems that the problem first appears on April 15 with the State Info patch, # 631
and only in the multi-thread case. I tried many older other exe without any problem.

And the problem is still present in latest SF #678

The position fen is 
Q7/8/8/2K1p1k1/8/8/8/1q6 b - - 2 64

This Is a  5-men position
The half move clock is 2, so we are 98 half moves away from the 50-move rule.

According to 
https://syzygy-tables.info/?fen=Q7/8/8/2K1p1k1/8/8/8/1q6_b_-_-_0_1
There are 2 winning moves, Qg1, (DTZ 18 DTM 134), or Kf4, (DTZ 58 DTM 160)
These number are the required half-moves

According to http://www.shredderchess.com/online-chess/online-databases/endgame-database.html
There are 2 winning moves, Qb1-g1, (DTM 68), or Kg5-f4, (DTM 81)
These number are the required full-moves

Problem is easy to reproduce.
I have a 4 CPU, and a syzygy 3-4-5 database

a) Start stockfish.exe

run the following command 
(change D:\DataKu\Games\Chess\TB\Syzygy for whatever you have)

setoption name Threads value 4
setoption name SyzygyPath value D:\DataKu\Games\Chess\TB\Syzygy
position startpos moves g1f3 d7d5 e2e3 c7c5 d2d4 g8f6 c2c4 e7e6 b1c3 b8c6 a2a3 a7a6 d4c5 f8c5 b2b4 c5d6 c1b2 e8g8 c4d5 e6d5 f1e2 f8e8 e1g1 c8e6 a1c1 a8c8 b4b5 c6e5 f3e5 d6e5 d1d2 d8e7 b5a6 b7a6 e2a6 e5h2 g1h2 f6g4 h2g1 e7h4 f1e1 c8d8 c3b5 d5d4 b5d4 h4h2 g1f1 h2h1 f1e2 h1g2 e2d1 g4f2 d1c2 g2e4 a6d3 e6b3 c2b3 f2d3 b3a2 d8b8 b2c3 h7h5 c1d1 d3e1 d1e1 h5h4 e1g1 g7g6 g1e1 b8b6 c3b4 g6g5 d2f2 e8a8 a2b2 e4d3 d4b3 a8c8 e1f1 f7f6 f1b1 h4h3 e3e4 b6c6 b3c5 d3d6 b1c1 d6e5 b2a2 g8g7 f2g1 c6c5 c1c5 h3h2 g1g2 c8c5 b4c5 e5c5 g2h2 c5c4 a2b2 c4e4 h2g3 g5g4 b2c1 e4d4 c1c2 g7h6 c2b3 h6g5 a3a4 d4d5 b3b4 d5e4 b4b5 e4e5 g3e5 f6e5 a4a5 g4g3 a5a6 g3g2 a6a7 g2g1q a7a8q g1b1 b5c5
go movetime 500

etc...

Close SF

a) Sometimes the problem can happen on the very first call to
go movetime 500
(it will suggest the non-winning e5e4)

b) if many successive calls to go movestime 500
I would say that at the very least, 10 % of the time it goes with the wrong e5e4

However, with 
setoption name Threads value 1
I was not able to reproduce the problem.
It always go for the correct g5f4 (b1g1 would be fine too, but it never goes for it).

Another experiment:

setoption name Threads value 4
setoption name SyzygyPath value D:\DataKu\Games\Chess\TB\Syzygy
position fen Q7/8/8/2K1p1k1/8/8/8/1q6 b - - 2 64
go movetime 500

This time it never goes for g5f4, It will go instead for the 
correct alternative b1g1 or the wrong e5e4

Also, if I use setoption name Threads value 2
the problem happens less often than with value 4

**Comment by Rocky640** [comment]
Another observation: with smaller 
go movetime 100
the problem happens much more often

And with go depth, it does not happen.

**Comment by joergoster** [comment]
@Rocky640 In case of go depth we don't pick another thread as best thread. At least not after my patch https://github.com/official-stockfish/Stockfish/commit/dc0030de4fdece2851dd0072c9aea53695ed90ce

If this is the case, we maybe have to be more careful when to pick another thread and its best move.

**Comment by joergoster** [comment]
@Rocky640 To be more clear, in case of using TBs, we most likely need to be more careful when picking another thread.

**Comment by Rocky640** [comment]
Thanks for the explanation, but I don't know much about search, you can be sure I will not be the one who will fix this !

However, the problem was not there before #631, so someone must look there.

**Comment by joergoster** [comment]
Ah, before this patch we made sure that all helper threads are searching the same root moves with
```
              th->rootMoves = rootMoves; 
```
It seems #631 somehow broke this?!
@zamar @mcostalba Can you please have a look?

**Comment by mcostalba** [comment]
I will give it a look.

**Comment by joergoster** [comment]
Above mentioned statement must be put back in place. To make sure that all helper threads search the same moves as the main thread. Reason is if the root position is a tablebase position, the root moves will be filtered to only those which will preserve the win (or the draw in other cases).

**Comment by mcostalba** [comment]
@joergoster please see ThreadPool::start_thinking() in thread.cpp, you will see the th->rootMoves = rootMoves assignment.

**Comment by joergoster** [comment]
@mcostalba Hmm, then there must be a subtle bug or a kind of race problem.

Printing the number of root moves with
```
      sync_cout << "Thread: " << idx << "   Number of root moves: " << rootMoves.size() << sync_endl;
```
right before the while loop (iterative deepening loop) I get the following:
```
without syzygy
Stockfish 030616 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
uci
id name Stockfish 030616 64 POPCNT
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Write Debug Log type check default false
option name Contempt type spin default 0 min -100 max 100
option name Threads type spin default 1 min 1 max 128
option name Hash type spin default 16 min 1 max 1048576
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 30 min 0 max 5000
option name Minimum Thinking Time type spin default 20 min 0 max 5000
option name Slow Mover type spin default 89 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 6 min 0 max 6
uciok
setoption name Threads value 7
position startpos moves g1f3 d7d5 e2e3 c7c5 d2d4 g8f6 c2c4 e7e6 b1c3 b8c6 a2a3 a7a6 d4c5 f8c5 b2b4 c5d6 c1b2 e8g8 c4d5 e6d5 f1e2 f8e8 e1g1 c8e6 a1c1 a8c8 b4b5 c6e5 f3e5 d6e5 d1d2 d8e7 b5a6 b7a6 e2a6 e5h2 g1h2 f6g4 h2g1 e7h4 f1e1 c8d8 c3b5 d5d4 b5d4 h4h2 g1f1 h2h1 f1e2 h1g2 e2d1 g4f2 d1c2 g2e4 a6d3 e6b3 c2b3 f2d3 b3a2 d8b8 b2c3 h7h5 c1d1 d3e1 d1e1 h5h4 e1g1 g7g6 g1e1 b8b6 c3b4 g6g5 d2f2 e8a8 a2b2 e4d3 d4b3 a8c8 e1f1 f7f6 f1b1 h4h3 e3e4 b6c6 b3c5 d3d6 b1c1 d6e5 b2a2 g8g7 f2g1 c6c5 c1c5 h3h2 g1g2 c8c5 b4c5 e5c5 g2h2 c5c4 a2b2 c4e4 h2g3 g5g4 b2c1 e4d4 c1c2 g7h6 c2b3 h6g5 a3a4 d4d5 b3b4 d5e4 b4b5 e4e5 g3e5 f6e5 a4a5 g4g3 a5a6 g3g2 a6a7 g2g1q a7a8q g1b1 b5c5
go depth 3
Thread: 0   Number of root moves: 30
Thread: 4   Number of root moves: 30
Thread: 3   Number of root moves: 30
Thread: 1   Number of root moves: 30
Thread: 5   Number of root moves: 30
Thread: 2   Number of root moves: 30
info depth 1 seldepth 1 multipv 1 score cp 74 nodes 430 nps 86000 tbhits 0 time 5 pv b1d3
info depth 2 seldepth 3 multipv 1 score cp 70 nodes 822 nps 137000 tbhits 0 time 6 pv b1d3 a8g2 g5f6 g2c6 f6g5
info depth 3 seldepth 5 multipv 1 score cp 83 nodes 2974 nps 424857 tbhits 0 time 7 pv b1d3 a8g2 g5f5 g2f2 f5e6
Thread: 6   Number of root moves: 30
bestmove b1d3 ponder a8g2
quit
```
Looks ok. All threads searching the same number of root moves.

```
with syzygy
Stockfish 030616 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
uci
id name Stockfish 030616 64 POPCNT
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Write Debug Log type check default false
option name Contempt type spin default 0 min -100 max 100
option name Threads type spin default 1 min 1 max 128
option name Hash type spin default 16 min 1 max 1048576
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 30 min 0 max 5000
option name Minimum Thinking Time type spin default 20 min 0 max 5000
option name Slow Mover type spin default 89 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 6 min 0 max 6
uciok
setoption name SyzygyPath value file:///home/oster/Downloads/syzygy-5men/syzygy 
info string Found 145 tablebases.
setoption name Threads value 7
position startpos moves g1f3 d7d5 e2e3 c7c5 d2d4 g8f6 c2c4 e7e6 b1c3 b8c6 a2a3 a7a6 d4c5 f8c5 b2b4 c5d6 c1b2 e8g8 c4d5 e6d5 f1e2 f8e8 e1g1 c8e6 a1c1 a8c8 b4b5 c6e5 f3e5 d6e5 d1d2 d8e7 b5a6 b7a6 e2a6 e5h2 g1h2 f6g4 h2g1 e7h4 f1e1 c8d8 c3b5 d5d4 b5d4 h4h2 g1f1 h2h1 f1e2 h1g2 e2d1 g4f2 d1c2 g2e4 a6d3 e6b3 c2b3 f2d3 b3a2 d8b8 b2c3 h7h5 c1d1 d3e1 d1e1 h5h4 e1g1 g7g6 g1e1 b8b6 c3b4 g6g5 d2f2 e8a8 a2b2 e4d3 d4b3 a8c8 e1f1 f7f6 f1b1 h4h3 e3e4 b6c6 b3c5 d3d6 b1c1 d6e5 b2a2 g8g7 f2g1 c6c5 c1c5 h3h2 g1g2 c8c5 b4c5 e5c5 g2h2 c5c4 a2b2 c4e4 h2g3 g5g4 b2c1 e4d4 c1c2 g7h6 c2b3 h6g5 a3a4 d4d5 b3b4 d5e4 b4b5 e4e5 g3e5 f6e5 a4a5 g4g3 a5a6 g3g2 a6a7 g2g1q a7a8q g1b1 b5c5
go depth 3
Thread: 0   Number of root moves: 2
Thread: 4   Number of root moves: 30
Thread: 5   Number of root moves: 30
Thread: 6   Number of root moves: 30
Thread: 1   Number of root moves: 30
Thread: 2   Number of root moves: 30
Thread: 3   Number of root moves: 30
info depth 1 seldepth 2 multipv 1 score cp 12353 nodes 728 nps 104000 tbhits 2 time 7 pv g5f4 a8f8 f4g4
info depth 2 seldepth 3 multipv 1 score cp 12353 nodes 867 nps 123857 tbhits 2 time 7 pv g5f4 a8f8 f4e4
info depth 3 seldepth 5 multipv 1 score cp 12353 nodes 2167 nps 270875 tbhits 2 time 8 pv g5f4 a8g2 b1c1 c5b5
bestmove g5f4 ponder a8g2
quit
```
Not ok. Only the root moves for the main thread are filtered by the tablebases.
Hope this helps.

**Comment by mcostalba** [comment]
I have open a pull request

https://github.com/official-stockfish/Stockfish/pull/690

**Comment by joergoster** [comment]
@mcostalba Thank you!
