### ISSUE TITLE
Set spin count for the critical section object

### ISSUE THREAD

**Issue by braich** [official-stockfish/Stockfish#738]
On Windows we use critical sections to implement thread lock and unlock functions. It is possible to specify the spin count for the critical section object. This can increase search speed on multiprocessor systems.

**Comment by mcostalba** [comment]
We use a Windows call that is compatible with old Windows versions, even Windows XP.

Other sync API have been introduced later and are not back compatible. Moreover current lazy SMP does not need heavy locking to work.

**Comment by braich** [comment]
InitializeCriticalSectionAndSpinCount and SetCriticalSectionSpinCount ARE supported by Windows XP.

**Comment by braich** [comment]
And Mictosoft states that

> You can improve performance significantly by choosing a small spin count for a critical section of short duration. For example, the heap manager uses a spin count of roughly 4,000 for its per-heap critical sections. 

But I do not have hardware to verify.

**Comment by mcostalba** [comment]
You don't have a Windows pc?

Seriously this is not an issue but eventually a potential improvement that
requires someone to write a patch and verify that is measurable better than
current master. Unlikely IMO due to how locking is used in lazy smp but I'd
love to be wrong...

Guess what?  In case you have a Windows pc you could do all by yourself:
all the needed software is available for free in these days of developers
heaven :-)

**Comment by braich** [comment]
I have windows pc with 2-cores CPU. And you are right, on my pc there is no measurable search speed difference, but I believe that such difference can be seen on pc with 20 cores.

**Comment by mcostalba** [comment]
Once you have a working patch you can ask someone with big hardware to test
it for you.

**Comment by mstembera** [comment]
@braich I made such a request here before.
https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/big$20hardware/fishcooking/30RO4EEBLnA/O5xqVlEeAwAJ
